### ISSUE TITLE
Sonoff Basic new Layout

### ISSUE THREAD

**Issue by reloxx13** [arendst/Sonoff-Tasmota#4515] opened 2018-12-03 08:03 UTC
Heya,

the Sonoff Basics got a new Board Layout.

GPIO14 is gone and now there is a GPIO2 (IO2 and its not a borehole!).

In the Template GPIO2 is disabled, so dunno if u want to add a new Layout or allow GPIO2 for the Sonoff Basic.

Workaround: Use Generic Template and set GPIOs yourself.

Template:
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/sonoff_template.h#L520

![https://forum.creationx.de/forum/index.php?thread/1254-sonoff-basic-neueste-version-gpio14/](https://forum.creationx.de/index.php?attachment/2641-pasted-from-clipboard-png/)

![https://forum.creationx.de/forum/index.php?thread/1254-sonoff-basic-neueste-version-gpio14/](https://forum.creationx.de/index.php?attachment/2640-pasted-from-clipboard-png/)

**Comment by Jason2866** [comment] 2018-12-03 08:38
Hello @reloxx13 
is it a real ITEAD Sonoff Basic? For me the typical ITEAD sticker on relais is missing.
Maybe just a (good?) clone...

**Comment by andrethomas** [comment] 2018-12-03 08:46
At least it seems they are addressing the thermal issue since this board appears to have 9 via's from the bottom of the ESP8266 chip coming through to the bottom onto what seems to be a much larger ground plane that in the older versions.

**Comment by andrethomas** [comment] 2018-12-03 08:49
@reloxx13 Is that a ESP8285 on there?

**Comment by reloxx13** [comment] 2018-12-03 10:08
@andrethomas yep, you will find better pictures here: https://smarthome.schimmer-media.de/forum/index.php?thread/2370-neuer-sonoff-basic-oder-ganz-altes-modell/&postID=26177#post26177

@Jason2866 im pretty sure those are orginal itead's
![https://smarthome.schimmer-media.de/forum/index.php?thread/2370-neuer-sonoff-basic-oder-ganz-altes-modell/&postID=26177#post26177](https://s15.directupload.net/images/181128/ve9qg968.jpg)

Some more infos here (in german):
https://forum.creationx.de/forum/index.php?thread/1254-sonoff-basic-neueste-version-gpio14/

https://smarthome.schimmer-media.de/forum/index.php?thread/2370-neuer-sonoff-basic-oder-ganz-altes-modell/

**Comment by andrethomas** [comment] 2018-12-03 10:23
@reloxx13 @Jason2866 

This is good news - so in future we will not have thermal issues with the new sonoff basic's I think.

**Comment by andrethomas** [comment] 2018-12-03 10:31
I think just adding GPIO2 to the Sonoff Basic template will not cause harm as GPIO2 is not used on the previous editions of the Sonoff Basic.

**Comment by andrethomas** [comment] 2018-12-03 10:32
Or it will be easier for user to select different version and template will dictate where POWER is.

**Comment by ascillato** [comment] 2018-12-03 10:36
I think that would be better and less confusing for people to just add gpio2 to the sonoff basic template

**Comment by ascillato** [comment] 2018-12-03 10:37
Lets make a PR and that Theo decides ;)

**Comment by andrethomas** [comment] 2018-12-03 10:48
Yeah, just adding GPIO2 is fine.

![image](https://user-images.githubusercontent.com/470015/49369269-b512d500-f6f9-11e8-9547-02f1fabddfde.png)

**Comment by arendst** [comment] 2018-12-03 11:46
Just add gpio2 please ;-)

**Comment by ascillato** [comment] 2018-12-03 11:49
@reloxx12 your call ;)

**Comment by andrethomas** [comment] 2018-12-03 15:30
https://github.com/arendst/Sonoff-Tasmota/pull/4518

**Comment by ascillato2** [comment] 2018-12-03 15:35
Closing as the PR has been made. Thanks everyone for sharing theirs ideas.

We also need to add this information to the wiki. I will do that later. Thanks.

**Closed by ascillato2** 2018-12-03 15:35 UTC
Labels: add to wiki, enhancement

**Comment by reloxx13** [comment] 2018-12-03 19:09
i wrote sth in the wiki for that, feel free to edit/move it, im not sure where to place it on the basic page.

https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Basic#new-board-layout

Version needs to be added if its released.

**Comment by jimmyhall82** [comment] 2018-12-05 20:09
How do I update the template used on my Tasmota sonoff? I flashed with most recent firmware but I don’t have gpio2 listed in the configuration template

**Comment by ascillato** [comment] 2018-12-05 20:10
Use latest Tasmota version 6.3.0.15 (http://thehackbox.org/tasmota/)

**Comment by reloxx13** [comment] 2018-12-05 20:16
(its not released now, its in the dev version)

**Comment by jimmyhall82** [comment] 2018-12-05 20:17
@ascillato thanks

**Comment by joydeepsaha05** [comment] 2018-12-09 08:11
@reloxx13 I have the same board and was trying to flash Tasmota, but it fails to get detected by my computer. Were you able to successfully flash it? Are the flashing steps different for the new board?

**Comment by andrethomas** [comment] 2018-12-09 15:31
@joydeepsaha05 

> Are the flashing steps different for the new board?

No, exactly the same.

**Comment by joydeepsaha05** [comment] 2018-12-10 03:56
@andrethomas Thanks for confirming. I was able to flash using a Raspberry Pi, must've been something wrong with my FTDI adapter.

**Comment by hudecitydave** [comment] 2018-12-19 22:44
THANKS for the work here!
Now I try to power up a SR505 PIR sensor on GPIO02/IO2. 
Has anyone found a 5V pin to get the needed power on the new board?
Thanks for info!

**Comment by ascillato** [comment] 2018-12-19 22:45
The sonoff basic R2 does not have enough power to power another device. Sorry. The hardware was not designed for that.

**Comment by hudecitydave** [comment] 2018-12-23 14:10
> 
> 
> The sonoff basic R2 does not have enough power to power another device. Sorry. The hardware was not designed for that.

Just a small update to that: I managed to solder a small cable to GPIO2/IO2, and ordered some HC-SR501 PIR Sensors. Bringing them to power with 3,3V works as charme. (like this: https://randomnerdtutorials.com/modifying-cheap-pir-motion-sensor-to-work-at-3-3v/)

Now we have the next room hassio enabeld :-)

**Comment by andrethomas** [comment] 2018-12-23 17:07
@hudecitydave Sure, it may work (for an undeterminable time), but it is not recommended.

**Comment by hudecitydave** [comment] 2018-12-23 18:02
> @hudecitydave Sure, it may work (for an undeterminable time), but it is not recommended.

You both are right. The device produces many false switch actions now. Not stable, not wife compatible.

But ... how to solve the "switch light on room movement" without an extra esp8266? Any hints for me?
Thanks, folks!

**Comment by andrethomas** [comment] 2018-12-23 18:06
> But ... how to solve the "switch light on room movement" without an extra esp8266? Any hints for me?

I think the obvious conclusion is an extra esp8266/wemos d1mini (or whatever you normally use for bare installations)

**Comment by tlpbu** [comment] 2018-12-26 22:31
@hudecitydave I am using [this AM312 PIR](https://www.aliexpress.com/item/Mini-IR-Pyroelectric-Infrared-PIR-Motion-Human-Sensor-Automatic-Detector-Module-high-reliability-12mm-x-25mm/32749737125.html?spm=a2g0s.9042311.0.0.27424c4dFWe9sq&dp=99791c0a21e48cf8853fef7b5a93156e&af=843361&cv=47843&afref=&mall_affr=pr3&dp=99791c0a21e48cf8853fef7b5a93156e&af=843361&cv=47843&afref=&mall_affr=pr3&aff_platform=aaf&cpt=1545862862805&sk=VnYZvQVf&aff_trace_key=10c9ef61636c4ec09ded881b548aa18e-1545862862805-03435-VnYZvQVf&terminal_id=033a0522a0184d888e9f8fdf12e0547f) with Sonoff Basic (older model without GPIO2) for 5 months or so.
Setup Tasmota rule to control PIR as you and your wife needs and you’re golden.

**Comment by andrethomas** [comment] 2018-12-28 11:37
@ivanmarban It should work the same as GPIO14 - I don't know why they changed the pin from GPIO14 to GPIO2 - perhaps it was easier to route on the new pc board design.

**Comment by eric-void** [comment] 2018-12-28 12:11
@ivanmarban @andrethomas Looking at tasmota documentation, it's not true that "it should work the same as GPIO14"
In https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs#restrictions, you can read "GPIO2 can’t be low at boot, so you can’t connect a switch to it".
If the documentation tells the truth, using GPIO2 as a switch could give some problems (if the device reboots for any reason and the switch is off the device will not boot normally).

**Comment by ivanmarban** [comment] 2018-12-28 13:06
@eric-void @andrethomas any workaround ?

**Comment by Jason2866** [comment] 2018-12-28 14:47
Yes, there are restrictions with GPIO2. 
So it is not recommended to use switches, just only momentary switches.
If you want tu use a other GPIO you have to solder direct on the ESP chip.

**Comment by freemiumdev** [comment] 2019-01-05 19:15
how do you flash the new model? I can not get it into FLASH MODE
when i try to fash with Arduino ide i get this error:
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

**Comment by andrethomas** [comment] 2019-01-05 20:12
No difference to the old one.

Disconnect all power, hold down push button while powering up usb - keep button down for 2 seconds and then flash as per wki... no difference.

Some picky devices want you to hold the button down during the entire process - not sure if you maybe have one of these.

**Comment by czarnikjak** [comment] 2019-01-06 21:19
Any luck With connecting DHT22 to GPIO02 on these new boards?
Can’t get it to work, tasmota doesn’t see the sensor at all.

**Comment by akasma74** [comment] 2019-01-07 22:49
Yeah, tried to use DHT22 (on a board) with a new version of Sonoff Basic.
Shows null/null in web interface.
Ended up connecting the sensor to the old Sonoff Basic, and it works a treat.

Still want to have a solution for new boards as it's a bit odd and looks like a bug.

**Comment by czarnikjak** [comment] 2019-01-07 22:58
Mine is not even showing anything in the Web interface.
As if dht22 is not getting enough power.
I am supplying the 3.3v to it from the sonoff itself ( using vcc and ground
pins next to tx and rx)

**Comment by freemiumdev** [comment] 2019-01-09 01:04
> No difference to the old one.
> 
> Disconnect all power, hold down push button while powering up usb - keep button down for 2 seconds and then flash as per wki... no difference.
> 
> Some picky devices want you to hold the button down during the entire process - not sure if you maybe have one of these.

i've tried, but not working

**Comment by cosmos1978** [comment] 2019-01-10 18:39
So no more switches with the new layout.
Can someone tell me which pin is gpio14 ?

**Comment by andrethomas** [comment] 2019-01-10 18:57
![image](https://user-images.githubusercontent.com/470015/50990279-4b68c080-151a-11e9-929f-220738de3a88.png)

Its a corner pin so if you're good you will achieve it :)

**Comment by andrethomas** [comment] 2019-01-10 19:00
![image](https://user-images.githubusercontent.com/470015/50990434-b2867500-151a-11e9-9afd-e60b67aaa1df.png)

**Comment by andrethomas** [comment] 2019-01-10 19:11
Actually, GPIO4 (D2) is also a good possible candidate...

![image](https://user-images.githubusercontent.com/470015/50990948-28d7a700-151c-11e9-96b7-ed263e361e95.png)

**Comment by andrethomas** [comment] 2019-01-10 19:21
![image](https://user-images.githubusercontent.com/470015/50991567-9cc67f00-151d-11e9-874c-53c9f3e80bea.png)

**Comment by cosmos1978** [comment] 2019-01-10 21:44
Wow many thanks. I know what to do tomorrow. 😀

**Comment by andrethomas** [comment] 2019-01-10 21:53
You're welcome - remember to use flux paste to avoid solder bridges between the pins and inspect your work with a magnifier after you have soldered, then tack the wire down with some hot glue a cm or so away from the chip so it does not come loose easily.

**Comment by 1300371** [comment] 2019-01-12 22:11
> @eric-void @andrethomas any workaround ?
I use `GPIO3` (RX) and `GND` connected to a wall switch and it works great.
Moreover, it doesn't require additional soldering as i already solder it to flash.

**Comment by czarnikjak** [comment] 2019-01-13 13:41
Any possibility to use RX or TX pins to connect DHT sensor?

**Comment by Jason2866** [comment] 2019-01-13 17:10
Why not? connect it to RX

**Comment by petersendk** [comment] 2019-01-13 23:33
Hi forgot to write i tried 3,3v i tried 5,5v i tried adress 48, i tried adress 49 without luck. i also tried generic sonoff, but after configuring  and at first boot it stopped.

**Comment by petersendk** [comment] 2019-01-14 09:06
It seems that a scan for i2c sensors take about 5 minutes first time after pwr up, after this everything ok.

**Comment by cosmos1978** [comment] 2019-01-14 21:34
Does gpio 3 (rx) have a buildin pullup resistor ?
I have a sonnof with long cables now on gpio 2 and since there is no pullup lots of ghost switching.

**Comment by andrethomas** [comment] 2019-01-15 11:03
@cosmos1978 Yes

**Comment by cbugeja** [comment] 2019-01-16 00:08
Apologies but I'm still very very new to all this...
I need to set up a Sonoff Basic with 2 external sensors (reed switches) to work independently from the relay. The cable from the sensors to the sonoff needs to be 10mtrs max. 
I was thinking of using GPIO4 and GPIO14. Is this a good choice once the sensors are not momentary switches?
Would I need to attach any resistors to these to avoid what @cosmos1978 referred to as ghost switching?

**Comment by georgia088** [comment] 2019-01-18 13:53
> @ivanmarban
> 
> > @eric-void @andrethomas any workaround ?
> 
> I use `GPIO3` (RX) and `GND` connected to a wall switch and it works great.
> Moreover, it doesn't require additional soldering as i already solder it to flash.

I am new to all this, so I am trying to understand.  You are soldering wires from GPIO3 (RX) and GND to a standard Wall Switch (not momentary/rocker).  Then setting GPIO3 to (GPIO3 Serial In - Switch1 (09)) in Tasmota?

Is this correct? Does it work as it should?  

Thanks!!

**Comment by BrunoZumba** [comment] 2019-01-18 14:31
> PIO3 Serial In

Yes, my friend. That's perfect. I just did it this morning and works like a charm.
As I said in my reply just above this one: i just want someone to confirm that this setting has no other problems. But i can confirm that is working so far :)

**Comment by BrunoZumba** [comment] 2019-01-18 15:00
> > @ivanmarban
> > > @eric-void @andrethomas any workaround ?
> > 
> > 
> > I use `GPIO3` (RX) and `GND` connected to a wall switch and it works great.
> > Moreover, it doesn't require additional soldering as i already solder it to flash.
> 
> I am new to all this, so I am trying to understand. You are soldering wires from GPIO3 (RX) and GND to a standard Wall Switch (not momentary/rocker). Then setting GPIO3 to (GPIO3 Serial In - Switch1 (09)) in Tasmota?
> 
> Is this correct? Does it work as it should?
> 
> Thanks!!

Yes, my friend. That's perfect. I just did it this morning and works like a charm.
As I said in my reply just above this one: i just want someone to confirm that this setting has no other problems. But i can confirm that is working so far :)

**Comment by georgia088** [comment] 2019-01-18 16:04
> > > @ivanmarban
> > > > @eric-void @andrethomas any workaround ?
> > > 
> > > 
> > > I use `GPIO3` (RX) and `GND` connected to a wall switch and it works great.
> > > Moreover, it doesn't require additional soldering as i already solder it to flash.
> > 
> > 
> > I am new to all this, so I am trying to understand. You are soldering wires from GPIO3 (RX) and GND to a standard Wall Switch (not momentary/rocker). Then setting GPIO3 to (GPIO3 Serial In - Switch1 (09)) in Tasmota?
> > Is this correct? Does it work as it should?
> > Thanks!!
> 
> Yes, my friend. That's perfect. I just did it this morning and works like a charm.
> As I said in my reply just above this one: i just want someone to confirm that this setting has no other problems. But i can confirm that is working so far :)

Awesome! Do you have to install a pull up resistor, or does it work with a built in one?
P.S. I posted this same basic question as a new issue because this thread shows "closed".  I wasn't sure if it would get viewed.  I apologize!

**Comment by BrunoZumba** [comment] 2019-01-19 14:41
> > > > @ivanmarban
> > > > > @eric-void @andrethomas any workaround ?
> > > > 
> > > > 
> > > > I use `GPIO3` (RX) and `GND` connected to a wall switch and it works great.
> > > > Moreover, it doesn't require additional soldering as i already solder it to flash.
> > > 
> > > 
> > > I am new to all this, so I am trying to understand. You are soldering wires from GPIO3 (RX) and GND to a standard Wall Switch (not momentary/rocker). Then setting GPIO3 to (GPIO3 Serial In - Switch1 (09)) in Tasmota?
> > > Is this correct? Does it work as it should?
> > > Thanks!!
> > 
> > 
> > Yes, my friend. That's perfect. I just did it this morning and works like a charm.
> > As I said in my reply just above this one: i just want someone to confirm that this setting has no other problems. But i can confirm that is working so far :)
> 
> Awesome! Do you have to install a pull up resistor, or does it work with a built in one?
> P.S. I posted this same basic question as a new issue because this thread shows "closed". I wasn't sure if it would get viewed. I apologize!

No, I didn't install any pull up resistor. It hasn't exploded nor set my house on fire yet, so far so good :)
 
But a few posts above AndreThomas said it has a buildin pull resistor already.

**Comment by 2016for** [comment] 2019-01-25 13:32
> > The sonoff basic R2 does not have enough power to power another device. Sorry. The hardware was not designed for that.
> 
> Just a small update to that: I managed to solder a small cable to GPIO2/IO2, and ordered some HC-SR501 PIR Sensors. Bringing them to power with 3,3V works as charme. (like this: https://randomnerdtutorials.com/modifying-cheap-pir-motion-sensor-to-work-at-3-3v/)
> 
> Now we have the next room hassio enabeld :-)

Installing PIR on GPIO2 isn't causing any problems like should be low on boot or something?
Someone suggested me to use GPIO1/TX for PIR, would that be ok/better/same as your GPIO2 connection?

**Comment by h4nc** [comment] 2019-01-25 14:57
Wanted to share how I modded my basic (with the new layout) to use the relay without power (230V).

I use these modded sonoffs to switch DC powered devices.

![img_8133-2](https://user-images.githubusercontent.com/25117255/51753175-737b2680-20b9-11e9-9415-c0747cc21316.jpeg)

1. Remove those wires 
2. cut the traces I marked red. Just must go through the whole pcb because the traces are on both sides. 
3. Connect two wires like in the picture (I use enamelled copper wire)

If someone wants to use this picture for documentation. You are welcome. Share it. Copy it. I don't mind.

**Comment by meingraham** [comment] 2019-01-25 15:12
@h4nc 

With your modification, what voltage needs to be supplied at the external input contacts to power the electronics? 3.3V or 5V?

**Comment by h4nc** [comment] 2019-01-25 15:23
@meingraham On the **input** side you still use AC 230V. 
With the modification you can use the relay to switch on and off what you want. It's like you turn on or off a switch. 
So you can switch 3.3V, 5V. Whatever you want but you will need a power supply. 
Just keep in mind that the wires in this mod are thin, so this mod is only for low power setups. 
With this you only switch the relay itself.



If you want to power your sonoff with DC than there is another model on the market (from itead). Search for "sonoff dc"

**Comment by meingraham** [comment] 2019-01-25 15:37
Ah, you've just made the relay a dry relay. Thanks.

**Comment by h4nc** [comment] 2019-01-25 15:50
meingraham’s posting made me think about if it is possible to power this moded Basic with DC current.

Could someone bith better knowledge explain why it is or it is not possible?

Mainly there are three parts that transform AC to DC.

Bridge of diods, transformer, capactor.

So if I put in 5V DC instead of 230V AC, the transformer is the only thing  (that I would think of) that could make issues.

As I don’t know if it transforms voltages fixed at 5/230 (so a certain percentage) or it transforms whatever voltage (E.g. 40v) comes to 5V.

If fixes percentage that putting in 5V wouldn’t work because than we would get out much less than 5V

**Comment by andrethomas** [comment] 2019-01-25 18:49
@h4nc I think its a terrifying idea.

For low voltage applications, it would be better to use Sonoff SV (Safe Voltage) https://www.itead.cc/sonoff-sv.html

**Comment by h4nc** [comment] 2019-01-25 19:59
I don‘t to do that. Just want to know what would happen.

**Comment by andrethomas** [comment] 2019-01-25 20:07
@h4nc usually when devices are used for purposes other than the original intention bad things happen. The problem with posting it here is that it gives other people bad ideas so I'll be removing it shortly.

**Comment by h4nc** [comment] 2019-01-25 23:58
It was just a theoretical question.

I don‘t understand why you also deleted my picture of the mod.
It only showed how to mod it to get a „relay only“ setup.

Try to understand first what my mod does.

The other question were only theoretical.

**Comment by andrethomas** [comment] 2019-01-26 14:11
> On the input side you still use AC 230V.

Thin wires close to AC input... then the user gets used to the relays only switching their DC load and forgets that there is high voltage AC on the input side and gets cremated... unless he is rubberman, of course.

I don't have a problem if someone wants to make a modification but posting information or answers to questions that could lead to the end of someone's life is irresponsible.

There are better ways to achieve what was explained in the modification, for example using a Sonoff SV or if you really want something that has isolated relays and is powered from AC then perhaps a Sonoff 4CH Pro would be safer.

Whichever way you look at it a user which does not already have the knowledge to do this modification without a "how to" should really not be doing it and it is for this reason that I removed it.

**Comment by h4nc** [comment] 2019-01-26 14:11
I don't want to fight either. If you know what you are doing this mod was/is not dangerous. However we are working on high voltage here, so sonoffs are kind of dangerous all the time (if you don't know waht you are doing).

As long as @andrethomas gives his ok for the picture to be uploaded again, I will not do it, as he is maindeveloper of this great project and I respect his decision.
But still I'd like to know whats wrong on my mod on his mind.

I tested my mod and it works fine. I use these kind of moded basics to trigger my garage doors. 

It also wasn't my idea at first place because I found this idea moths ago here https://forum.iobroker.net/viewtopic.php?t=10192. 
I uses this mod on my old basic and wanted to show the community how you can mod the new layout.

**Comment by andrethomas** [comment] 2019-01-26 14:13
> he is maindeveloper of this great project

Yes, it is a great project but I cannot take credit for "main developer" as that would be @arendst :)

**Comment by h4nc** [comment] 2019-01-26 14:19
> Whichever way you look at it a user which does not already have the knowledge to do this modification without a "how to" should really not be doing it and it is for this reason that I removed it.

I get that. Someone who knows whats going on, is able to do that without a how to.
For the record: Those thin wires I uses are isolated coper wires (so no short when they are pushed together).

> Yes, it is a great project but I cannot take credit for "main developer" as that would be @arendst :)
True, I messed that up. Only saw "andre"and it look similar to arendst, sry ;)
