### ISSUE TITLE
WiFi Hostname changed after resting the sonoff device 

### ISSUE THREAD

**Issue by mikroelektron** [arendst/Sonoff-Tasmota#5566] opened 2019-04-01 14:50 UTC
I'm using the latest Tasmota version 6.5, with ESP core 2.4.2.
I used the ESPtools for each time that i want to upload a new firmware, first i make full erase and then i upload the bin code.
### BUG DESCRIPTION
The problem is the WIFI host-name that appears in WiFi list, is changed after resting the module by applying 4 fast clicks on sonoff button. 
I have attached 2 pictures, as shown in first one, the host-name is sonoff-with last 6 char of mac address. After connect with it and make the configuration of wifi, then the module will be connected. I do reset by clicking the button 4 fast times. i got the result that clear in second picture. I do that several times and i got same result. Even the host-name is changed to ESP-with last 6 char of mac address, its still working if you want to connect with it. But i want to get fixed Host-name each time even i reset the module several times. 

![error11](https://user-images.githubusercontent.com/45847030/55336997-8ab60600-54a6-11e9-95ed-169b9ce15493.jpg)
![error22](https://user-images.githubusercontent.com/45847030/55337012-91447d80-54a6-11e9-94cc-8a5b9111ce38.jpg)

**Comment by ascillato2** [comment] 2019-04-01 14:51
Confirmated. Thanks for reporting.

**Comment by arendst** [comment] 2019-04-01 14:59
The hostname has always been derived using the following code:
```
  Format(mqtt_topic, Settings.mqtt_topic, sizeof(mqtt_topic));
  if (strstr(Settings.hostname, "%") != nullptr) {
    strlcpy(Settings.hostname, WIFI_HOSTNAME, sizeof(Settings.hostname));
    snprintf_P(my_hostname, sizeof(my_hostname)-1, Settings.hostname, mqtt_topic, ESP.getChipId() & 0x1FFF);
  } else {
    snprintf_P(my_hostname, sizeof(my_hostname)-1, Settings.hostname);
  }
```
So if hostname is defined with "%s_%04d" it will replace %s with formatted topic appended with the last four decimal characters of the MAC address.

What you experience is redundant naming caused by SDK which is out of control by Tasmota and core. The SDK might change hostname with what you see as ESP_\<6 character\> MAC address. This is not fabricated by Tasmota.

Sorry can't help here.

**Comment by mikroelektron** [comment] 2019-04-01 14:59
I also have used core 2.3.0 and 2.5 and i got same result.

**Comment by ascillato2** [comment] 2019-04-01 15:02
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed** 2019-04-01 15:02 UTC
Labels: wont/can't fix
