### ISSUE TITLE
Google Home not finding sonoff basic 

### ISSUE THREAD

**Issue by drbent15** [arendst/Sonoff-Tasmota#175] opened 2017-03-10 14:26 UTC
Hi, I have been try to get my Google Home to discover my sonoff basic for a while. When I turn on Wemo I see nothing in the console but when I turn on Hue I see this in the console even when I'm not running discovery it just keeps repeating:
Can you tell me What I'm doing worng?
Thanks
(192.168.1.16 is my Google Home and 192.168.1.5 is my Amazon Fire TV)

14:12:39 UPnP: HUE 3 response packets sent to 192.168.1.5:1290
14:13:04 UPnP: HUE 3 response packets sent to 192.168.1.16:57997
14:13:33 UPnP: HUE 3 response packets sent to 192.168.1.5:1290
14:14:26 UPnP: HUE 3 response packets sent to 192.168.1.5:1290
14:15:20 UPnP: HUE 3 response packets sent to 192.168.1.5:1290
14:16:04 UPnP: HUE 3 response packets sent to 192.168.1.16:57997
14:16:13 UPnP: HUE 3 response packets sent to 192.168.1.5:1290
14:16:59 MQTT: tele/sonoff/STATE = {"Time":"2017-03-10T14:16:59", "Uptime":11, "POWER":"OFF", "Wifi":{"AP":1, "SSID":"NETGEAR2", "RSSI":64}}
14:17:04 UPnP: HUE 3 response packets sent to 192.168.1.16:57997
14:17:05 UPnP: HUE 3 response packets sent to 192.168.1.5:1290
14:18:00 UPnP: HUE 3 response packets sent to 192.168.1.5:1290
14:18:04 UPnP: HUE 3 response packets sent to 192.168.1.16:57997

**Comment by davidelang** [comment] 2017-03-19 14:17
duplicate of #173

**Closed by davidelang** 2017-03-19 14:17 UTC
Labels: duplicate, help wanted
