### ISSUE TITLE
Uptime Reset after loosing Wifi Signal at sOnOffPow 1 + 2

### ISSUE THREAD

**Issue by LurchiStromberg** [arendst/Sonoff-Tasmota#3207] opened 2018-07-13 10:02 UTC
HI!
I recognized, that the Uptime is resetted, after the Router restarts or lost Wifi Signal.

I think it would be better to be able to set a Starttime, when Pow starts Monitoring, that wont reset after loosing Wifi or else.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ x] Hardware used : 
- [ x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment] 2018-07-13 11:15
I think it should be possible with a rule and using a variable
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#5-use-of-variables-and-tele-

**Comment by LurchiStromberg** [comment] 2018-07-13 11:40
Thank you for your Answer!
I am not that much into that Stuff...

Can you give me a hint how that should work connected to my "Problem" with the Uptime?
Its funny that nobody else recognize that "Issue"
Because.
Isnt it an urgent Information how long the Pow is running already if i want to calculate the periode and usage of Power recorded?
Sure i can do that at FHEM log for example but it would be nice, if Tasmota would support that out of stock.
Just in the Overview Page to see, total kw/h and since when its recorded. 
Urgent and useful Information if you ask me.

**Comment by Frogmore42** [comment] 2018-07-13 14:32
Log showing the issue?
Status 0

You probably have it configured to reset when it loses connection.  Uptime is the amount of time the device has been up, which is working as designed.

I use the POW for measurements and have had no issue other than on a power failure it can sometimes go backwards, but that is a pretty rare occasion and saving to flash more frequently would wear it out faster.

The POW provides the power used today, and total.  If you want more detail you reply need to store the data in your home automation system, or something like emoncms, or influxdb.

**Comment by LurchiStromberg** [comment] 2018-07-13 15:30
Well sure, like I said, its possible in FHEM.

But you have an Overview in Tasmota and i think the Job is easy to do (of course not for me) to have a Point, what shows since what date / time the total ammount of kw/h is running.

**Comment by arendst** [comment] 2018-07-14 13:42
No need to store anything. Just change wificonfig to WIFI_WAIT (5) and the device will not restart when your router is lost and uptime will keep counting...

**Comment by LurchiStromberg** [comment] 2018-07-14 14:18
Oh, is it really that easy?
Looks like i have to learn a lot still :(

**Comment by Frogmore42** [comment] 2018-07-14 15:44
That will work till there is a power failure.  When there is a power failure, the POW will reset, so uptime will reset to 0. If it has access to the internet when power comes back it will know what time it really is, but it currently only logs that information.  If it doesn't have access to the internet, it has no way of knowing what time it really is.

**Comment by Jason2866** [comment] 2018-07-14 15:54
@Frogmore42 I tried it with rules. -> failed. Maybe it is a easy solution but i dont see it.
I am still thinking it should be possible (store it in a variable and read it)

**Comment by ascillato2** [comment] 2018-08-27 22:40
Hi,

Closing as the original topic of the issue (losing uptime because tasmota resets after wifi lost) can be solved as explained by wificonfig 5 command

Please, ask to reopen if needed. Thanks

**Closed by ascillato2** 2018-08-27 22:40 UTC
