### ISSUE TITLE
Can't get time from ntpserver with DHCP

### ISSUE THREAD

**Issue by Gwenselah** [arendst/Sonoff-Tasmota#5283] opened 2019-02-19 21:21 UTC
**Describe the bug**
Some of Tasmota Pow R2 does not get time from time server. 
00:21:23 MQT: tele/sonoff/STATE = {"Time":"1970-01-01T00:21:23","Uptime":"0T00:20:24","Vcc":3.418,"SleepMode....

I tried timezone 99
I tried to setup the ntpserver to internal or external ntp server. I use ip or dns lookup.
I reseted the sonoff (reset 4) and reconfigured the device.
Firmware: Sonoff-Tasmota 6.4.1 

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [ ] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ :  Sonof Pow R2
- [X] _Development/Compiler/Upload tools used_ : Atom Editor, and Inplace Upgrade of the tasmota firmware
- [X] _If a pre-compiled release or development binary was used, which one?_ : No
- [X] _You have tried latest release or development binaries?_ : yes, i tried the inplace upgrade button
- [ ] _Provide the output of command_``status 0`` :
```
00:33:14 MQT: stat/sonoff/RESULT = {"Time":"1970-01-01T00:33:14","Uptime":"0T00:32:15","Vcc":3.418,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":1,"SSId":"XXX","BSSId":"34:81:C4:F8:99:F2","Channel":6,"RSSI":86}}```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment] 2019-02-19 23:24
Hi,

Sorry, can't reproduce your issue. My pows are working fine. 

Please, check your network. This issue had happened before and most of the time is just a misconfiguration on your router or firewall. Just once was that ntp servers were down for a couple of hours.

**Comment by jziolkowski** [comment] 2019-02-20 15:41
@Gwenselah make sure your DHCP server sends correct NTP option as well. Tasmota is based on Arduino core, which takes this info and makes it primary (which causes problem with DHCP servers sending bad or empty options for NTP)

**Comment by Gwenselah** [comment] 2019-02-20 19:23
Hello,
thank you for your replies.
At the moment i have 4 Sonof Pow R2 in the same wlan. All have the 6.4.1 firmware. 2 of them get the correct time, the other 2 not.
Now I upgraded one to version 6.4.1.17 with core 2.5.0. this didn't solved the issue.
Are there some debugging commands to trace the getting time process?

Kind regards.

**Comment by jziolkowski** [comment] 2019-02-21 07:05
Come and join us at our discord. There were users with this problem. Might provide more help.
https://discord.gg/Crj7tCJ

**Comment by ascillato2** [comment] 2019-02-22 20:53
Hi,

Any news on this issue?

**Comment by Gwenselah** [comment] 2019-02-23 15:39
No, I setup a ntp server on my raspberry pi, but nothing changed. I increased the debug log, but there is nothing in it, which would help.
I will go over to discord now

**Comment by Gwenselah** [comment] 2019-02-23 16:22
Now I think i got it.
If you use DHCP on the sonoff and your DHCP server sends no or incorrect ntp option, then you can not use "ntpserver1 <IP>" to set an internal ntp server. You can set it, but it will not work. You have to set a satic ip on the sonoff addiotionally.
Version  6.4.1.17

**Comment by ascillato** [comment] 2019-02-23 17:24
Very interesting! Thanks for sharing this.
That explains why I couldn’t reproduce the issue.

Thanks, now we have a workaround for people with this NTP issue for the DHCP in their router until something can be done in the code.

**Comment by andrethomas** [comment] 2019-02-25 06:34
Its a SDK issue - if NTP server exists (configured correctly or not) on the same IP as the DHCP server (no setting for NTP server necessary on DHCP settings) then the SDK automatically uses the NTP service it assumes to be good on the same IP of the DHCP server... or at least this has been my observation.

**Comment by arendst** [comment] 2019-02-25 18:52
So as it is SDK related you will have to use a workaround by adding one or two additional NTP servers using command ``ntpserver2`` and ``ntpserver3``.

**Comment by jziolkowski** [comment] 2019-02-26 13:35
@arendst it doesn't change anything. We've tried it with some discord users some time ago. The solution is to use DHCP server with proper NTP option configured in the lease.

@Gwenselah you've discovered what I basically told you in my first response.

**Comment by Gwenselah** [comment] 2019-02-26 16:39
@jziolkowski 
Please consider that many people only have dhpc "server" running on routers like Fritzbox and yes, may be I missunderstood you.
For those people my workaround it is easier then setup an run a real DHCP Server.
So, please stay polite.

**Comment by ascillato2** [comment] 2019-02-28 18:39
Closing this issue as it is has been answered. https://github.com/arendst/Sonoff-Tasmota/issues/5283#issuecomment-465630518

**Closed by ascillato2** 2019-02-28 18:39 UTC
Labels: bug, workaround
