### ISSUE TITLE
need button trigger user_application function without relay

### ISSUE THREAD

**Issue by martinmatias** [arendst/Sonoff-Tasmota#4467] opened 2018-11-27 03:23 UTC
Hi, I'm working with Tasmota and Stepper Motor (using a4988 driver).
I'm using user_application as explained by tobox and made a web page were I can drive the stepper in both directions.
Now I also want to drive the stepper using button in 2 direction and 2 momdes each directtion: Single Press 2000 steps, Hold 2 sec until a limit (hardcoded into my function using hall efect sensor).

I've read rules page into wiki (example 16), but I'm not able to drive button without relay (I dont have remaining pins for a dummy relays). I've tried example with buttontopic 0 and buttontopic 1, but only work with a relay connected.
Please, need help about how to make switch work without relay and how to activate a user defined function.

Regards
Martin

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [X] Development/Compiler/Upload tools used : Arduino IDE
- [X] Hardware used : Wemos D1 Mini
- [X] If a pre-compiled release or development binary was used, which one? 
No, compiled
- [X] You have tried latest release or development binaries? :
Version 6.3.0.2-2_4_2:
```

**Comment by digiblur** [comment] 2018-11-27 12:45
if you do a rule of something like "on button1#state do...." then you don't need any relay companion with it.

**Comment by martinmatias** [comment] 2018-11-27 14:17
Hi @digiblur, thanks for your reply. As previously commented, I've tried different buttontopic configuration and none of them worked for me withput relay defined. Also, if worked, I dont know how to call a "user defined" function from the rule.
Thanks
Martin

**Comment by digiblur** [comment] 2018-11-27 15:18
Maybe start with a blank config, with the rules you'll want buttontopic and/or switchtopic set to 0 if you are using rules.  I do know it works though as I have a device with 2 or 3 buttons and 1 relay and the other 2 buttons push out an MQTT message anytime they are interacted with which in turn kicks off some other things in my home automation software.  

Start small with a simple 1 relay config and 2 button/switch configuration, once you learn the rules you'll see how powerful things really become.

**Comment by martinmatias** [comment] 2018-11-27 15:24
I'm starting simple, following examples ( wiki rules example 16 that send MQTT messages on double click or hold), but when I change configuration without relays (I mean, configure none where I had relay) it dont work anymore. When I enable again relay it return working. Unfortunatelly, I dont have remaining pins for a dummy relay (I need to buttons). I can't find the way to enable button without relay. After that, I have to deal about how to trigger "user defined" function from rule.

**Comment by digiblur** [comment] 2018-11-27 15:43
So here's a quick sample that I know works on a board as I've shown in some of my tutorial videos with PIR sensors on switches.  I've used switches instead of button configs but I do have their switchmodes set as switchmode 5/6 for toggles/hold states.

Start fresh and do a simple D1 as Relay1, D2 as Switch1, D3 as Switch2 (or whatever pins you want).  Switchtopic is 0.    

Switch1 will flip the relay1 back and forth as intended.  If you do a rule of "rule1 on switch2#state do publish testing/stuff %value% endon" you'll see switch2 doesn't need a relay companion and will just push out the states.  Don't forget to turn the rule1 on with "rule1 1"

**Comment by martinmatias** [comment] 2018-11-27 15:46
Ok, I'll try as soon as possible. if it works, then I'll configure D1 as none and see if it continues working. Then I'll try with buton instead of switch(I need button).

Regards
Martin

**Comment by ascillato2** [comment] 2018-11-27 17:15
Full example at: https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#16-using-an-external-button-with-single-press---double-press-and-hold

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Closed by ascillato2** 2018-11-27 17:15 UTC
Labels: question
