### ISSUE TITLE
Sonoff Touch Flash error:

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#2830] opened 2018-05-25 21:39 UTC
any way I get to this message:
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
I'm connecting it ok!
why?!

**Comment by Frogmore42** [comment] 2018-05-26 02:48
There are lots of other issues in the list with similar sounding problems.  There is some information in the wiki on how to flash.  There are you tube videos on it too.  Please review those first to see if they solve your problem.

There are many things that can cause the issue you are seeing.  None of them are actually Tasmota issues.  They are usually caused by user error or bad power or USB serial converters.

**Comment by shayshtern** [comment] 2018-05-26 06:31
Is it possible to flash it OTA? SonOTA Works with Sonoff Touch? Any experience?

**Comment by reloxx13** [comment] 2018-05-26 18:59
check sonota wiki for supported devices.

**Comment by appde** [comment] 2018-06-20 21:04
@shayshtern Reducing upload_speed in platformio.ini file fixes most of the issues:
```
upload_speed = 115200
;upload_speed = 512000
```

**Comment by ascillato2** [comment] 2018-07-10 10:35
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.

**Closed by ascillato2** 2018-07-10 10:35 UTC
