### ISSUE TITLE
Flash S20 v1.3 ?

### ISSUE THREAD

**Issue by ElecTriX666** [arendst/Sonoff-Tasmota#1669] opened 2018-01-21 19:13 UTC
I have flashed over 8 basics without any problems but this S20 EU is not responding no matter what I do.
Tried flipping the TX / RX around but no difference.

- Soldered a 4-pin header (has worked great on the basic).
- Connected: GND TX RX VCC (from top to bottom)
- Press button for 2-3 seconds while attaching VCC
- Settings in Arduino (port is inactive because not inserted while taking screenshot)

![s20-settings](https://user-images.githubusercontent.com/35463138/35197922-5817a8ae-fee7-11e7-84e5-c9c04efd3c53.PNG)

No matter what I do I always get:

> warning: espcomm_sync failed
> error: espcomm_open failed
> error: espcomm_upload_mem failed
> error: espcomm_upload_mem failed

Anyone? I checked some videos on youtube and I am doing what everyone else has done, but they have always had v1.0 boards so don't know if any different?

**Comment by gajotnt** [comment] 2018-01-21 21:58
Flash size 1024 (no spiffs)

**Comment by ElecTriX666** [comment] 2018-01-21 22:15
@gajotnt I dont have that option??

![151657281256877362749](https://user-images.githubusercontent.com/35463138/35199623-d54fb474-ff00-11e7-8f17-ada9d3090de7.jpg)

**Comment by ElecTriX666** [comment] 2018-01-21 23:04
Still doesn't work and same error..

**Comment by gajotnt** [comment] 2018-01-21 23:08
Are you holding GPIO 0 to ground when connecting the programer?

**Comment by ElecTriX666** [comment] 2018-01-21 23:15
@gajotnt 

Pushing down the button while connecting VCC, tried holding for 2-3 seconds then letting go but also tried holding down button constantly.

Have they changed so button is not GPIO0 any more?

**Comment by gajotnt** [comment] 2018-01-21 23:24
Can you post some pics of the board? Maybe someone can tell if there are changes.

**Comment by ElecTriX666** [comment] 2018-01-21 23:30
![img_20180122_002759](https://user-images.githubusercontent.com/35463138/35200277-60f253b0-ff0b-11e7-8000-e7ae671be94c.jpg)
![img_20180122_002752](https://user-images.githubusercontent.com/35463138/35200278-611aace8-ff0b-11e7-8e61-7996093852a2.jpg)
![img_20180122_002746](https://user-images.githubusercontent.com/35463138/35200279-613f219a-ff0b-11e7-92e2-72302ea24fb2.jpg)
![img_20180122_002739](https://user-images.githubusercontent.com/35463138/35200280-6167b358-ff0b-11e7-8ec9-989f640fd11c.jpg)
![img_20180122_002752](https://user-images.githubusercontent.com/35463138/35200281-618f05c0-ff0b-11e7-9447-e8d3881498c2.jpg)
![img_20180122_002832](https://user-images.githubusercontent.com/35463138/35200282-61b36cc6-ff0b-11e7-87ca-0c2a1e4038ec.jpg)

**Comment by ElecTriX666** [comment] 2018-01-22 16:19
"Unknown" sounds really bad..

![img_20180122_171830](https://user-images.githubusercontent.com/35463138/35231176-6693b8f8-ff98-11e7-9dcb-57d94e52693d.png)

**Comment by ElecTriX666** [comment] 2018-01-22 16:22
Right.. After a reboot it works and I have v1.5.5. OTA here I come!

**Comment by xelarep** [comment] 2018-01-22 23:04
Had a similar problem in PlatformIO - used firmware.bin and esptool:
`cd Sonoff-Tasmota-master/.pioenvs/sonoff-DE
cp ~/Downloads/esptool-2.2/esptool.py .
python esptool.py --port /dev/cu.usbserial-AH01CDYO erase_flash
python esptool.py --port /dev/cu.usbserial-AH01CDYO write_flash -fs 1MB -fm dout 0x0 firmware.bin`

**Comment by gjlawran** [comment] 2018-02-17 19:54
@xelarep Thanks worked for me - after I changed the flash size to _detect_
`esptool.py --port COM11 write_flash -fs detect -fm dout 0x0 firmware.bin`

**Comment by algozzy** [comment] 2018-03-13 10:36
Similar problem but works like a charm with the flash size detect

**Comment by NicoBijl** [comment] 2018-06-02 22:03
I have two S20 EU v1.3 here, but got issues flashing them. 
Tried to flash one, no luck, keeps restarting after the flash. 
Then connected the second one (unchanged) to the ewelink app, and it is firmware 1.6. 

Is that a issue? or can i still do wired flash? using platformio..?
Looks like the flash on the first device went all right, but maybe someone can help me with the restart issue? 

I even tried setting  WIFI_CONFIG_TOOL to WIFI_MANAGER, but can't find the wifi AP.. 

This is not my first sonoff/tasmota, but it might be the first S20 v1.3.

**Comment by wb441** [comment] 2018-06-24 10:38
I was able to flash Tasmota to my Type E S20 back to back with a 4CH Pro Rev2.
For the latter, it showed up in my network, I could enter MQTT properties & control it from HASSIO.
However, the S20 doesn't show up. Do any of you guys see my mistake? Any differences to be expected betw 4CHProR2 and S20?

![image](https://user-images.githubusercontent.com/40491548/41818270-6b88cfa2-77ab-11e8-897f-0c5bb5ef6938.png)

**Comment by domhaas** [comment] 2018-07-10 20:07
Flashed successfully a current tasmota to a S20 v1.3 EU. Used a Pi3 for the connection. Didn't need to set the flash-size:
`esptool.py --port /dev/ttyS0 write_flash -fm dout 0x0 sonoff.bin`

**Comment by Ugagen** [comment] 2018-08-14 19:03
I had the same problem. 
Connection the wires rx-rx tx-tx solved the problem.

**Comment by ascillato** [comment] 2018-08-23 20:57
Hi,

Closing as lasts comments said that the issue is solved. Ask to reopen if needed. Thanks

**Closed** 2018-08-23 21:00 UTC
