### ISSUE TITLE
Tuya Module (54) on 6.6.0 gives 6 power switches

### ISSUE THREAD

**Issue by john5788** [arendst/Sonoff-Tasmota#6039] opened 2019-07-07 19:31 UTC
Tuya dimmer (KS-7011) works fine on 6.5.0, but upgrading to 6.6.0 converts the device into something that has 6 power channels and the dimmer slider no longer works. See attached images.

![unknown](https://user-images.githubusercontent.com/9289163/60772989-fe257000-a0b2-11e9-93d1-e650418f6ef5.png)

![unknown (1)](https://user-images.githubusercontent.com/9289163/60772994-02ea2400-a0b3-11e9-8a0d-4e532042d7a2.png)

The device reports back to HomeAssistant as multiple switches instead of a light with the update. Toggling the leftmost bit in the web UI toggles the light switch on and off.

Using this template: https://blakadder.github.io/templates/zemismart-ks-7011.html

**Comment by Jason2866** [comment] 2019-07-07 19:36
@s-hadinger can you take a look into? Just selecting module 54 (Tuya) results in this.
Thx!

**Comment by s-hadinger** [comment] 2019-07-07 20:33
This part of Tasmota is still obsure to me. I will try to see when the regression happened.

**Comment by arendst** [comment] 2019-07-07 20:51
I'll investigate tomorrow.

**Comment by s-hadinger** [comment] 2019-07-07 20:57
I'm exploring commits. Up to https://github.com/arendst/Sonoff-Tasmota/commit/ab9baf2ac074280ea3fb3b008d8878cae66b547d (6.5.0.13) it still works.

**Comment by arendst** [comment] 2019-07-07 20:59
I did some changes in tuya in one of the latest commits ...

**Comment by s-hadinger** [comment] 2019-07-07 21:03
And broken in https://github.com/arendst/Sonoff-Tasmota/commit/12da2fd6f9b1e4ef4c2eb078aaeea425b695a8aa

**Comment by arendst** [comment] 2019-07-08 09:52
Caused by commit aaacb20 (thirug010) which uses uninitialised, undocumented and messy param setting (SetOption38) to simulate amount of switches.

As the use of param SetOption38 was not documented the same parameter is used and initialised with 6 by IRRemote support resulting in 6 toggles pop up.

Performing command ``SetOption38 1`` could be used as a workaround if IRReceive was enabled in the binary. This is not always the case making this issue even more problematic.

I will need to dig into this further and would request PR suppliers to more thoroughly test their submitted PR's.

To be continued.

**Comment by arendst** [comment] 2019-07-08 10:44
Use SetOption41 to increment number of relays/switches. Default set to zero to supply legacy support.

**Comment by thirug010** [comment] 2019-07-08 14:21
@arendst, My apologies for not using with the proper document Setting parameter Index

**Comment by arendst** [comment] 2019-07-08 14:23
@thirug010 accepted ;-)

**Comment by ascillato2** [comment] 2019-07-08 19:02
Closing as this issue has been fixed. Thanks :+1:

**Closed by ascillato2** 2019-07-08 19:02 UTC
Labels: bug, fixed

**Comment by sonybansi** [comment] 2019-09-02 21:40
WiFi dimmer worked fine on full brightness and make a flikring at low brightness on Tasmota v6.5.0 , but after upgrading to Tasmota 6.6.0 show 6 switchs and  dimmer not working more. I tried to setoption 38 and 41 but no changes. See attached images.
![Screen Shot 2019-09-02 at 23 18 20](https://user-images.githubusercontent.com/28208396/64133685-6dc88a80-cdd8-11e9-89e1-328bd9815d5c.png)

![Screen Shot 2019-09-02 at 23 19 03](https://user-images.githubusercontent.com/28208396/64133692-7751f280-cdd8-11e9-89e4-3fb85815b55e.png)


![Screenshot_20190902-232229_AliExpress](https://user-images.githubusercontent.com/28208396/64133754-e0d20100-cdd8-11e9-8a19-b9425cfcd9d2.jpg)

![20190902](https://user-images.githubusercontent.com/28208396/64133904-ee3bbb00-cdd9-11e9-8c1e-4353c8a5748d.jpg)

**Comment by ascillato** [comment] 2019-09-02 21:51
Upgrade to latest 6.6.0.9. It is fixed in latest version

**Comment by sonybansi** [comment] 2019-09-02 23:20
Thanks! but dimmer not working just flashing a + led.

![Screen Shot 2019-09-03 at 00 47 16](https://user-images.githubusercontent.com/28208396/64135184-1cbf9300-cde6-11e9-8478-4b64de4914fd.png)

![Screen Shot 2019-09-03 at 00 48 01](https://user-images.githubusercontent.com/28208396/64135187-1fba8380-cde6-11e9-9f54-51733c706687.png)

![Screen Shot 2019-09-03 at 00 46 55](https://user-images.githubusercontent.com/28208396/64135428-a5d7c980-cde8-11e9-82e7-3bf72a4155f0.png)
![2019-09-03-01-11-38](https://user-images.githubusercontent.com/28208396/64135453-e6374780-cde8-11e9-855f-b5a7f9ecaa44.gif)
