### ISSUE TITLE
NX-SP201

### ISSUE THREAD

**Issue by awk2019** [arendst/Sonoff-Tasmota#5215] opened 2019-02-13 15:17 UTC
I have flashed two NX-SP201 dual switch with Tasmota via tuya-convert on one and cracked on open for wired serial flash.
When I use power monitoring via a custom template(HLW8012) I get a software watchdog resets about every 40-60 minutes. Do any one have any ideas on this. 

Pin out per tuya-convert compatible device list.
GPIO0: Led1i, GPIO4: Button1, GPIO5: HLW8012 CF, GPIO12: Relay1, GPIO13: Button2, GPIO14: HLWBL CF1, GPIO15: Relay2, GPIO16 HLWBL SEL

**Comment by Jason2866** [comment] 2019-02-13 15:32
`Status 0` is missing. I have no crystal ball :-)

**Comment by awk2019** [comment] 2019-02-13 16:26
What information is needed from status 0

**Comment by Jason2866** [comment] 2019-02-13 17:01
All. Just copy paste from webconsole.

**Comment by awk2019** [comment] 2019-02-13 17:33
18:26:53 CMD: status 0
18:26:53 MQT: stat/DualOutLet2/STATUS = {"Status":{"Module":61,"FriendlyName":["DualOutlet2A","DualOutlet2B"],"Topic":"DualOutLet2","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
18:26:53 MQT: stat/DualOutLet2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/sonoff.bin","RestartReason":"Software Watchdog","Uptime":"0T00:17:30","StartupUTC":"2019-02-13T17:09:23","Sleep":50,"BootCount":81,"SaveCount":454,"SaveAddress":"F7000"}}
18:26:53 MQT: stat/DualOutLet2/STATUS2 = {"StatusFWR":{"Version":"6.4.1(sonoff)","BuildDateTime":"2019-02-13T11:03:23","Boot":4,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
18:26:53 MQT: stat/DualOutLet2/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SECRET",""],"TelePeriod":15,"SetOption":["00208009","558180C0","00000400"]}}
18:26:53 MQT: stat/DualOutLet2/STATUS4 = {"StatusMEM":{"ProgramSize":571,"Free":432,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440A1","FlashMode":3,"Features":["00000809","1FDAE794","000383A0","23B617CE","0001BBC0"]}}
18:26:53 MQT: stat/DualOutLet2/STATUS5 = {"StatusNET":{"Hostname":"Benlink","IPAddress":"192.168.1.90","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"SECRET","Webserver":2,"WifiConfig":4}}
18:26:53 MQT: stat/DualOutLet2/STATUS6 = {"StatusMQT":{"MqttHost":"SECRET","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_F9D903","MqttUser":"SECRET","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
18:26:53 MQT: stat/DualOutLet2/STATUS7 = {"StatusTIM":{"UTC":"Wed Feb 13 17:26:53 2019","Local":"Wed Feb 13 18:26:53 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:02","Sunset":"18:06"}}
18:26:53 MQT: stat/DualOutLet2/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
18:26:53 MQT: stat/DualOutLet2/STATUS10 = {"StatusSNS":{"Time":"2019-02-13T18:26:53","ENERGY":{"TotalStartTime":"2019-02-07T03:09:41","Total":0.166,"Yesterday":0.040,"Today":0.125,"Power":51,"ApparentPower":63,"ReactivePower":37,"Factor":0.81,"Voltage":123,"Current":0.514}}}
18:26:53 MQT: stat/DualOutLet2/STATUS11 = {"StatusSTS":{"Time":"2019-02-13T18:26:53","Uptime":"0T00:17:30","Vcc":3.423,"SleepMode":"Normal","Sleep":50,"LoadAvg":19,"POWER1":"ON","POWER2":"OFF","Wifi":{"AP":1,"SSId":"SECRET","BSSId":"SECRET","Channel":4,"RSSI":100}}}

**Comment by Jason2866** [comment] 2019-02-13 18:22
Try precompiled version from http://thehackbox.org/tasmota/sonoff.bin
Probably your selfcompiled is buggy...
Before flashing Tasmota erase whole flash with esptool erase_flash

**Comment by awk2019** [comment] 2019-02-13 18:31
I had the same problem with the precompiled dev tasmota on both devices,and the released version dose not have a template for the nx-sp201 dual plug switch. Also its a glued to together device.

**Comment by Jason2866** [comment] 2019-02-13 18:51
Try reset 2  Probably fragments left in flash from original firmware causes your issues
It erases all flash behind tasmota and resets to defaults.

**Comment by awk2019** [comment] 2019-02-13 19:23
After tasmota update and reset 2, I configured the device per 
GPIO0: Led1i, GPIO4: Button1, GPIO5: HLW8012 CF, GPIO12: Relay1, GPIO13: Button2, GPIO14: HLWBL CF1, GPIO15: Relay2, GPIO16 HLWBL SEL
then when I celebrated the voltage it started resting every 2-10 seconds.
When I use it with out power monitoring it will work with out a problem.

**Comment by Jason2866** [comment] 2019-02-13 19:31
"SP201",
     GPIO_LED1_INV,    // GPIO00 Led (1 = On, 0 = Off) - Power status
     GPIO_NRG_SEL_INV, // GPIO03 HLWBL HJL-01 Sel output (1 = Voltage)
     GPIO_KEY1,        // GPIO04 Button 1
     GPIO_HJL_CF,      // GPIO05 HLW8012 BL0937 or HJL-01 CF power
     GPIO_REL1,        // GPIO12 Relay1 (0 = Off, 1 = On)
     GPIO_KEY2,        // GPIO13 Button 2
     GPIO_NRG_CF1,     // GPIO14  HLWBL BL0937 or HJL-01 CF1 current / voltage
     GPIO_REL2,        // GPIO15 Relay2 (0 = Off, 1 = On)

**Comment by Jason2866** [comment] 2019-02-13 19:35
I dont see you have configured GPIO3

**Comment by awk2019** [comment] 2019-02-14 20:14
no good I tried multiple variations of the sensor pin settings and reset 2 the NX-SP201 with no improvement, I have two devices behaving exactly the same way.
I can get power readings for a 30 to 60 minutes before a software watchdog reset, and the power readings are correct in comparison to a KILL A WATT meter with BL0937 sensor.

**Comment by Jason2866** [comment] 2019-02-14 21:31
I am out of ideas. Since we (support team) dont own this device we cant help you further...

**Comment by ascillato2** [comment] 2019-02-15 00:45
Please, try http://thehackbox.org/tasmota/020500/sonoff.bin and then do a reset 5

**Comment by awk2019** [comment] 2019-02-15 01:29
no good ether, I just going to give up on power monitoring for now.

**Comment by Jason2866** [comment] 2019-02-15 16:41
Have you tried the preconfigured template for this model?
It is in latest dev firmware....

**Comment by DavinKD** [comment] 2019-02-16 02:54
I just flashed a couple of these and have the same issue when power monitoring is configured.

**Comment by Jason2866** [comment] 2019-02-16 10:54
Out of luck, since we dont have this device..
Maybe someone finds a solution.

**Comment by DavinKD** [comment] 2019-02-16 17:31
I'm digging into the code and will report back if I figure out the issue.

**Comment by DavinKD** [comment] 2019-02-16 18:01
Started up Syslog server and caught this.

sonoff-7484 ESP-RSL: INFO3 = {"RestartReason":"Fatal exception:2 flag:2 (EXCEPTION) epc1:0x3ffff140 epc2:0x00000000 epc3:0x00000000 excvaddr:0x3ffff140 depc:0x00000000"}

**Comment by DavinKD** [comment] 2019-02-16 22:36
Not 100% sure yet, but the issue seems to be caused by running a status 0 command, perhaps while it's in the middle of taking a power reading.  When I removed that command from my SmartThings device handler, the issue seems to have stopped.  I need to let it run for a while to be sure.

**Comment by DavinKD** [comment] 2019-02-17 00:19
Ok, so when I disable the 200ms ticker for energy checking, I can run status 0 many times with no crashing.  There's definitely something there.

**Comment by DavinKD** [comment] 2019-02-18 19:50
FYI, today I rebuilt from the latest dev branch and it all seems to be working.  
/shrug

Using the following GPIO Pin arrangement (please note I prefer to control the blue LED as a separate relay instead of it being GPIO_LED1_INV since there is already a red led that turns on with the relays).

  { "SP201",           // Orange Tech 2 in 1 Smart Socket Wifi Mini Outlet  with Energy Monitoring
                       // https://www.amazon.com/gp/product/B07L63S731
                       // used https://github.com/arendst/Sonoff-Tasmota/wiki/Tuya-OTA for flashing Tasmota via OTA
     GPIO_REL3_INV,    // GPIO00 Led (1 = On, 0 = Off) - Power status
     0, 0,
     GPIO_NRG_SEL_INV, // GPIO03 HLWBL HJL-01 Sel output (1 = Voltage)
     GPIO_KEY1,        // GPIO04 Button 1
     GPIO_HJL_CF,      // GPIO05 HLW8012 BL0937 or HJL-01 CF power
                       // GPIO06 (SD_CLK   Flash)
                       // GPIO07 (SD_DATA0 Flash QIO/DIO/DOUT)
                       // GPIO08 (SD_DATA1 Flash QIO/DIO/DOUT)
     0,                // GPIO09 (SD_DATA2 Flash QIO or ESP8285)
     0,                // GPIO10 (SD_DATA3 Flash QIO or ESP8285)
                       // GPIO11 (SD_CMD   Flash)
     GPIO_REL1,        // GPIO12 Relay1 (0 = Off, 1 = On)
     GPIO_KEY2,        // GPIO13 Button 2
     GPIO_NRG_CF1,     // GPIO14  HLWBL BL0937 or HJL-01 CF1 current / voltage
     GPIO_REL2,        // GPIO15 Relay2 (0 = Off, 1 = On)
     0, 0
  }

**Comment by Jason2866** [comment] 2019-02-18 19:56
Could you add your setup to the wiki with a template and close this issue?
Thank you
https://github.com/arendst/Sonoff-Tasmota/wiki/User-created-templates

**Comment by DavinKD** [comment] 2019-02-18 19:58
Sorry, I didn't open the issue.  I'll get the template added shortly unless @balvant813 already did.  I copied from his merge request.

**Comment by Jason2866** [comment] 2019-02-18 20:05
Ahh, yes. we will close. Thx for adding in wiki

**Comment by andrethomas2** [comment] 2019-02-18 20:08
Closing this issue as requested above.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Closed by andrethomas2** 2019-02-18 20:08 UTC
Labels: awaiting feedback, template missing, troubleshooting

**Comment by DavinKD** [comment] 2019-02-18 20:18
No worries.  Wiki updated.  Hopefully I did it correctly.  There's many devices on Amazon which are the same, but I just linked one of them.

**Comment by DavinKD** [comment] 2019-02-18 21:15
@Jason2866

Should the template functionality work the same as modifying the sonoff_template.h file as in the change by @balvant813?

https://github.com/arendst/Sonoff-Tasmota/pull/5180/commits/dae9ecb4d66d8eea897742d0f488f5ce303aa13c

Reason I ask, is because when I compile my own bin file from the latest dev branch using this template file, everything works great.  However, when I went to test the template I created in the wiki, the watchdog reboots re-appeared.

**Comment by Jason2866** [comment] 2019-02-18 21:24
Should be the same... I will investigate tomorrow

**Comment by DavinKD** [comment] 2019-02-18 22:51
@Jason2866 

I was wrong about which branch @balvant813 was working from.  His is actually 6.4.1.15.  Maybe something with the HLW8012/HLJ-01 broke between those versions?  I can consistently compile his check-in and it works fine with my device.  The latest (.17) gives the watchdog error whether I use the template, set the pins manually for a generic device or change the sonoff_template.h similar to his release.

All this being said, I have a version that works now, and maybe it would be a waste of time for you to investigate, but I'm happy to pay for you to get one to test with.  They're only $16.

**Comment by arendst** [comment] 2019-02-19 13:00
@DavinKD few questions:

- on what core version do you get these watchdog errors?
- when you received exceptions did they always have the same address (as long as you used the same binary)?

**Comment by DavinKD** [comment] 2019-02-19 15:36
@arendst 

If I'm reading things correctly in platformio.ini, I believe they are both using 2.4.2

[core_active]
; Select one core set for platform and build_flags
;platform                  = ${core_2_3_0.platform}
;build_flags               = ${core_2_3_0.build_flags}
platform                  = ${core_2_4_2.platform}
build_flags               = ${core_2_4_2.build_flags}
;platform                  = ${core_2_5_0.platform}
;build_flags               = ${core_2_5_0.build_flags}
;platform                  = ${core_stage.platform}
;build_flags               = ${core_stage.build_flags}


I very rarely get anything more than "Software Watchdog" or "Hardware Watchdog".  Below are a few exceptions.

2/16/2019 4:59 PM,Debug,192.168.1.148,sonoff-7484 ESP-RSL: INFO3 = {""RestartReason"":""Fatal exception:0 flag:2 (EXCEPTION) epc1:0xc003b015 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000""}

2/16/2019 2:51 PM,Debug,192.168.1.148,sonoff-7484 ESP-RSL: INFO3 = {""RestartReason"":""Fatal exception:0 flag:2 (EXCEPTION) epc1:0xc003201d epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000""}

2/16/2019 1:56 PM,Debug,192.168.1.148,sonoff-7484 ESP-RSL: INFO3 = {""RestartReason"":""Fatal exception:0 flag:2 (EXCEPTION) epc1:0x313a2267 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000""}

2/16/2019 1:18 PM,Debug,192.168.1.148,sonoff-7484 ESP-RSL: INFO3 = {""RestartReason"":""Fatal exception:0 flag:2 (EXCEPTION) epc1:0x3a22656d epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000""}

2/16/2019 12:57 PM,Debug,192.168.1.148,sonoff-7484 ESP-RSL: INFO3 = {""RestartReason"":""Fatal exception:0 flag:2 (EXCEPTION) epc1:0x3a22656d epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000""}

**Comment by arendst** [comment] 2019-02-19 16:14
All exceptions are 0 - Illegal Instruction. This normally looks like a power supply failure.

The watchdogs are harder to trace...

To be certain, these watchdogs do appear out of the blue or is the device acting on commands like ``status 0``?

**Comment by DavinKD** [comment] 2019-02-19 16:31
It only seems to occur when running a status 0 and only while energy monitoring is enabled (GPIO set for the HLW8012).  You have to run a few status 0 commands, but it will consistently crash after doing it 3-10 times.  I usually wait about 3-5 seconds in between.  However, I have seen it happen when I'm not testing and my SmartThings device handler calls the status 0 (every 5 minutes).  I had a lamp hooked up and let it run for hours and I occasionally would hear the relay click and the light flash off then on.  That's what clued me in that something was wrong.  I can of course, speed up the failure by sending a bunch of status 0 command in close proximity.

**Comment by arendst** [comment] 2019-02-19 16:34
Ok. Makes sense. I experience watchdogs too on a simple wemos device with status 0 but only on core 2.5.0.

So I don't think it's an issue with your device but more a problem in the code either tasmota, core or sdk.

I'll have to dig deep.

**Comment by DavinKD** [comment] 2019-02-19 16:39
Thanks.  I've been unable to make it crash on .15 (from @balvant813) with core 2.4.  I've not checked extensively as to whether he made any other changes besides to the template.

**Comment by arendst** [comment] 2019-02-19 16:42
Just tried TasmoAdmin (which sends status 0 commands as does SmartThings) and was greeted with a lot of clicking relays of devices I updated yesterday to 6.4.1.17 and core 2.4.2 as results of watchdogs...

I'll have to dig deep fast...

**Comment by DavinKD** [comment] 2019-02-19 16:47
Wish I knew the code well enough to be of use.  I'm still figuring out where everything is and what it all does.

**Comment by Jason2866** [comment] 2019-02-19 18:46
@arendst  may you take a look here https://github.com/esp8266/Arduino/commit/7745e99046bcbfbee5058376f30ca213146c3439

**Comment by arendst** [comment] 2019-02-19 19:17
@Jason2866 I know what's going on there but for now I noticed we have an issue with both core 2.4.2 and 2.5.0 related to tasmota versions between 6.4.1.14 (ok) and 6.4.1.16 (faulty).

@andrethomas  and @ascillato2 know about it.

**Comment by andrethomas** [comment] 2019-02-19 19:36
Its something which causes a software watchdog reset from the core in core_esp8266_main.cpp:134 loop_task

That's all we know for now... to be continued...

**Comment by jziolkowski** [comment] 2019-02-20 10:04
I've flashed my 4CH with 6.4.17 on 2.5.0 and it restarted on statuses 3,4,5 and 9. Other were fine.

**Comment by KPK75** [comment] 2019-02-20 10:08
No watchodgs when command "status 0" is sent via MQTT ( 6.4.1.17 / 2.5.0 ).

**Comment by arendst** [comment] 2019-02-21 08:52
Thx for your input. What we know sofar is that it is initiated by HTTP only; Serial and MQTT are fine.

Investigating.

**Comment by jziolkowski** [comment] 2019-02-21 10:04
The statuses I wrote above were initiated via MQTT. I'll re-flash the device with core 2.5.0 and test again.

**Comment by arendst** [comment] 2019-02-21 10:21
@jziolkowski I now know the source of the "hangs" is not http initiated.

It fails while executing the status mqtt result message way before sending the results to http console or client.

Investigating.

**Comment by arendst** [comment] 2019-02-21 11:05
Got something with debug enabled and memfree set to 1:

```
11:50:17 DBG: FreeRam 22392, FreeStack 1040 (MqttPublishDirect)
11:50:17 MQT: stat/wemos2/STATUS2 = {"StatusFWR":{"Version":"6.4.1.17(sonoff)","BuildDateTime":"2019-02-21T11:46:57","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
```
and
```
11:59:47 DBG: FreeRam 23088, FreeStack 2224 (MqttPublishDirect)
11:59:47 MQT: stat/wemos2/STATUS2 = {"StatusFWR":{"Version":"6.4.1.14(sonoff)","BuildDateTime":"2019-02-21T11:57:28","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
```
Using the info from the occasional exception and the firmware.map the problem is on PubSubClient::publish having not enough stackspace.

Will need to investigate why 6.4.1.14 stackspace is soo much larger than 6.4.1.17 at the time of executing command status 0.

To be continued.

**Comment by arendst** [comment] 2019-02-21 13:52
Caused by lack of stack space it might intermittent go in exception or watchdog. the latest dev frees some stack space and should be more stable.

Give it a try and let me know if it fails again.

**Comment by DavinKD** [comment] 2019-02-21 15:09
I'll try it tonight.  I didn't bring one to work with me today.

**Comment by DavinKD** [comment] 2019-02-24 23:57
Sorry for the slow reply.  I had ordered a few more of these and they just came in today.  That way I didn't have to mess with ones I already had in use.  I just flashed with the latest dev build (6.4.1.18(41a342c-sonoff)).  I am unable to make it crash by running a status.  Looks like we're good now.  Thanks for the fix.

**Comment by molpie** [comment] 2019-02-26 13:32
Hello, two days ago I installed version 6.4.1.19 on Blitzwolf smart sockets. The hardware and software watchdogs that caused the restart have disappeared. I often use TasmoAdmin and don't see any problems.

**Comment by andrethomas** [comment] 2019-02-26 14:25
@molpie Thanks for the feedback. The bug was isolated to around 6.4.1.15-6.4.1.16 and assume stable from 6.4.1.18. Appreciate the feedback.

**Comment by cmccambridge** [comment] 2019-03-28 16:59
@DavinKD From a mechanical side, how did you do your wiring for the SP201? I've got an SP201 that failed OTA conversion, and am trying to work out a reasonable wiring method to access the UART pins on the daughter board... At the moment I think I'll either need some very long probes, or to desolder the AC plug itself if I want to avoid permanently cutting away the back plastic housing. Any tips?

**Comment by DavinKD** [comment] 2019-03-28 17:00
I only used OTA.  I've never tried to open these.

**Comment by cmccambridge** [comment] 2019-03-28 17:44
Oops, I'm sorry about that, thanks for the heads up. I lost track of who was who during the thread. I actually meant to ask @awk2019 for physical access tips based on the comment about:

> tuya-convert on one and cracked on open for wired serial flash.

(FWIW, so far this does not look to be a very physical-modification-friendly device... have to break a glue seal to open it initially, and still TBD what the best serial access route is. OTA on my other one was vastly preferable :) )

**Comment by ed-war-d** [comment] 2019-05-30 08:35
Hi! Could't you tell me where I can find the pinouts (Rx,Tx, 3.3V) for flashing the NX-SP201?

**Comment by Jason2866** [comment] 2019-05-30 10:54
@ed-war-d  if you provide photos probably yes

**Comment by ed-war-d** [comment] 2019-05-30 11:10
![1559214516484_1](https://user-images.githubusercontent.com/51192328/58629243-95ddb480-82e4-11e9-8d7c-ce5e67b35651.JPEG)
![1559214501699_2](https://user-images.githubusercontent.com/51192328/58629256-a0984980-82e4-11e9-8cb0-9d2a4fc2fc03.JPEG)

**Comment by Jason2866** [comment] 2019-05-30 11:53
A photo of the blue Module from the other side will give the needed infos

**Comment by ed-war-d** [comment] 2019-05-30 12:54
![1559220839014_3](https://user-images.githubusercontent.com/51192328/58634157-3b982000-82f3-11e9-8504-89be614d1e27.JPEG)

**Comment by cmccambridge** [comment] 2019-05-30 13:07
Heh, you definitely took the smarter approach to this one @ed-war-d :) I struggled with desoldering the AC connector to free the PCB, so I ended up reprogramming mine with the assistance of a very long needle point logic probe reaching all the way under the PCB between the PCB and the back case plastic to reach the TX pin from behind, and used a GND connection at one of the small headers for the buttons and LEDs on either side.

The pinout can be found on page 6 of this datasheet for the ESP8266-S3: https://fccid.io/2AKBPESP8266-S3/User-Manual/User-Manual-3594791

Overlaid on your image, it looks like this:
![58634157-3b982000-82f3-11e9-8504-89be614d1e27_LI](https://user-images.githubusercontent.com/1765921/58634716-a163b800-82b1-11e9-8c59-5143ef2f306d.jpg)

Note that the signals are named here with respect to the ESP8266. Meaning: the TX pin here is ESP8266's transmit pin, and you'd want to connect it to your UART adapter's RX pin.

**Comment by ed-war-d** [comment] 2019-05-30 13:18
Thanks

**Comment by ed-war-d** [comment] 2019-05-30 13:24
Where is the GPIO0: Led1i ?

**Comment by cmccambridge** [comment] 2019-05-30 13:25
For completeness for future readers, here are a couple photos of how I did my reflash without removing the AC ground pin.

Needle point logic probe to 2nd pin (`TX`) underneath PCB:
![sp201_probe](https://user-images.githubusercontent.com/1765921/58635535-c527fd80-82b3-11e9-97fa-195a4e63f291.jpg)
![sp201_tx](https://user-images.githubusercontent.com/1765921/58635547-ca854800-82b3-11e9-9af8-7abc75449886.jpg)

Soldered on to `IO0` (Brown wire), `RX` (Orange wire) and `VCC` (Black wire) at board edge:
![sp201_io0_rx_vcc](https://user-images.githubusercontent.com/1765921/58635610-eab50700-82b3-11e9-9c3d-c3c7cce3996b.jpg)

Plugged into `GND` in switch/LED daughterboard connector:
![sp201_gnd](https://user-images.githubusercontent.com/1765921/58635637-fef90400-82b3-11e9-858d-6dec7c83f894.jpg)

**Comment by cmccambridge** [comment] 2019-05-30 13:28
> Where is the GPIO0: Led1i ?

Sorry about that... until I pulled out those photos I had forgotten this device didn't route it to a button and I had to solder directly to it. Updated the annotated photo above, or in my photos it's the brown wire.

**Comment by ed-war-d** [comment] 2019-05-30 13:44
I've done it! Thanks!

**Comment by ed-war-d** [comment] 2019-05-30 13:48
What device I should select in Module type menu?

**Comment by cmccambridge** [comment] 2019-05-30 13:55
I configured mine using an SP-201 template from here: https://blakadder.github.io/templates/sp201dual.html

General instructions on templates here: https://github.com/arendst/Sonoff-Tasmota/wiki/Templates#importing-templates

**Comment by ed-war-d** [comment] 2019-05-30 14:12
With the template {"NAME":"SP-201","GPIO":[31,0,0,131,17,134,0,0,21,18,132,22,0],"FLAG":0,"BASE":45} I have 2 switches (not 2). Is this OK?

**Comment by ed-war-d** [comment] 2019-05-30 14:17
![2019-05-30 4](https://user-images.githubusercontent.com/51192328/58639021-c6cae300-82fe-11e9-8f76-b3ddf07eb1ac.png)

**Comment by ed-war-d** [comment] 2019-05-30 14:18
It seems I should to have got 2 switches

**Comment by DavinKD** [comment] 2019-05-30 15:15
The third "relay" is for the led.

**Comment by meingraham** [comment] 2019-05-30 15:28
The new LedLink feature in 6.5.0.12 may allow removal of this virtual relay for the LED. If you have questions on it's use, ping me over on Discord.

P.S. @DavinKD I was able to clean up the KS-604S config using this new feature.

**Comment by ed-war-d** [comment] 2019-05-30 16:59
Thanks

**Comment by rlowens** [comment] 2019-09-06 03:23
For future reference for any others that need to manually-flash an "NX-SP201" Smart Plug 2-in-1, there are 2 versions that I have just flashed. The Type A version pictured above in this thread with the 14-pin ESP8266-S3 module (with metal shield as pictured) can most easily be flashed with these connections:
Programmer RX solder to front of module, 2nd pad from the right.
Programmer TX bend a small hook into the tinned end of the wire and hook behind that pad you just soldered to.
Programmer 3.3V connect to pin 1 on the left or right end headers (left pin 1 is furthest from the module, right pin 1 is closest to the module).
Programmer GND connect to pin 5 on the left or right end header.
Jumper pin 4 (GPIO 0 for the blue status LEDs) to pin 5 (GND) on the left or right end header. Only needed during boot to put the chip in programming mode, but it is fine to leave it connected while you program.
![Dilisens SP201 type A module wires](https://user-images.githubusercontent.com/35885181/64397175-85dd1b80-d01d-11e9-9da9-3345b766f018.jpg)
![Dilisens SP201 type A pins](https://user-images.githubusercontent.com/35885181/64397177-8aa1cf80-d01d-11e9-83c1-6a027d819870.jpg)

The (newer or knock-off?) Type B version has a green module without metal shield (or onboard LED that the ESP8266-S3 has) labeled "E2S-B, 20XX.1X.17" on the back, with 15 staggered contacts (vs the 14 even contacts on the ESP8266-S3 module). And the header's on the left and right have very different pinout. Here's the comparison:
![Dilisens SP201 type A vs B top](https://user-images.githubusercontent.com/35885181/64398352-c048b780-d021-11e9-9eb1-e93e1967f76a.jpg)
![Dilisens SP201 type A vs B side](https://user-images.githubusercontent.com/35885181/64398357-c2ab1180-d021-11e9-876a-bcfcbadd7dc6.jpg)

The pinout on this module matches the 11-pad[ Tuya TYWE2S](https://fccid.io/2ANDL-TYWE2S/User-Manual/Users-Manual-3596121) module except with 4 more pads on the left side (2 more on the front and back). Here's the full pinout of the "E2S-B":
![Dilisens SP201 type B module wires](https://user-images.githubusercontent.com/35885181/64398415-ff770880-d021-11e9-9157-aa209e1c3828.jpg)
And the pads on the back of the module:
![Dilisens SP201 type B module back](https://user-images.githubusercontent.com/35885181/64398430-09990700-d022-11e9-9dc5-997193d2a165.jpg)
Side view:
![Dilisens SP201 type B side view front](https://user-images.githubusercontent.com/35885181/64398443-19185000-d022-11e9-8ae4-13db3251b719.jpg)

And the labels of the headers:
![Dilisens SP201 type B left end](https://user-images.githubusercontent.com/35885181/64398457-246b7b80-d022-11e9-9a39-f935775292b1.jpg)
![Dilisens SP201 type B right end](https://user-images.githubusercontent.com/35885181/64398462-27ff0280-d022-11e9-84b2-bcdb8e69b439.jpg)

To flash the Type B version, I had to chop some plastic to access the bottom of the module since 3 of the pads we need are on the back:
Programmer RX solder to back of module, 4th pad from the right.
Programmer TX solder to back of module, 3rd pad from the right.
Programmer 3.3V solder to back of module, furthest pad on the right.
Programmer GND connect to pin 2 on the left or right end header.
Use a wire to touch from GND (pin2 on the left or right end header) to the "IO0" test pad on the back of the module while you power on the programmer.

**Comment by rlowens** [comment] 2019-09-06 03:46
The current Tasmota template for "Type A" is https://blakadder.github.io/templates/sp201dual.html
though I would update the Template from
{"NAME":"SP-201","GPIO":[31,0,0,131,17,134,0,0,21,18,132,22,0],"FLAG":0,"BASE":45}
to:
{"NAME":"NX-SP201 A","GPIO":[158,0,0,131,17,134,0,0,21,18,132,22,0],"FLAG":0,"BASE":45}
(so the blue LEDs are LedLinki instead of Relay3i)

The current template for "Type B" is https://blakadder.github.io/templates/dilisens_SP201.html but I'd update the Template from
{"NAME":"Dilisens SP201","GPIO":[0,0,131,0,133,132,52,21,18,22,17,0,0],"FLAG":0,"BASE":18}
to
{"NAME":"NX-SP201 B","GPIO":[0,0,131,0,134,132,157,21,18,22,17,0,0],"FLAG":0,"BASE":45}
(Base on BlitzWolf SHP (45) instead of Generic (18), use LedLink instead of Led1, use BL0937 CF (134) instead of HLW8012 CF (133) since it uses a BL0937 not an HLW8012).

Oh, and the Type A uses a voltage divider (R_upstream + R_downstream) / R_downstream of (2.4Mohm x2 + 1Kohm) / 1Kohm = 2401 where the Type B uses (1Mohm x2 + 1Kohm)/1Kohm = 2001. They both use a 1ohm current sense resister. But I just used a Kill-a-watt type device to manually calibrate the voltage/current/power when running my window AC.
