### ISSUE TITLE
Strange display behaviour with switch configured

### ISSUE THREAD

**Issue by Kedryn** [arendst/Sonoff-Tasmota#4185] opened 2018-10-27 17:23 UTC
**Describe the bug**
It's not really a bug, but a strange behaviour
If, with a display on a nodemcu, there is also a switch configured (like a PIR, Radar, or a physical switch), you have to make tricks to not have the switch turn off the display.

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [ x ] _Searched the problem in issues and in the wiki_
- [ x ] _Hardware used_ : wemos nodemcu
- [ x ] _Development/Compiler/Upload tools used_ : Arduino 1.8.6 
- [ ] _Provide the output of command_``status 0`` :
```
18:18:21 MQT: stat/home_sensors/STATUS = {"Status":{"Module":18,"FriendlyName":["node-casa","node-casa2"],"Topic":"home_sensors","ButtonTopic":"0","Power":3,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
18:18:21 MQT: stat/home_sensors/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"","RestartReason":"Software/System restart","Uptime":"0T00:50:36","StartupUTC":"2018-10-27T16:27:45","Sleep":0,"BootCount":24,"SaveCount":29246,"SaveAddress":"3F6000"}}
18:18:21 MQT: stat/home_sensors/STATUS2 = {"StatusFWR":{"Version":"6.2.1.18","BuildDateTime":"2018-10-27T00:45:46","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
18:18:21 MQT: stat/home_sensors/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxxxxxxx","yyyyyyyyyyyyyyyy"],"TelePeriod":300,"SetOption":["04008009","55818000","00000000"]}}
18:18:21 MQT: stat/home_sensors/STATUS4 = {"StatusMEM":{"ProgramSize":554,"Free":2516,"Heap":15,"ProgramFlashSize":4096,"FlashSize":4096,"FlashMode":2,"Features":["00000410","0FEEC684","000183A5","37FFBFCC","00003BC0"]}}
18:18:21 MQT: stat/home_sensors/STATUS5 = {"StatusNET":{"Hostname":"node-casa","IPAddress":"192.168.0.210","Gateway":"192.168.0.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.254","Mac":"5C:CF:7F:6E:35:A7","Webserver":2,"WifiConfig":5}}
18:18:21 MQT: stat/home_sensors/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.48","MqttPort":1883,"MqttClientMask":"home_sensors","MqttClient":"home_sensors","MqttUser":"admin","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
18:18:21 MQT: stat/home_sensors/STATUS7 = {"StatusTIM":{"UTC":"Sat Oct 27 17:18:21 2018","Local":"Sat Oct 27 18:18:21 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"07:29","Sunset":"17:38"}}
18:18:21 MQT: stat/home_sensors/STATUS10 = {"StatusSNS":{"Time":"2018-10-27T18:18:21","Switch1":"ON","ANALOG":{"A0":3},"DS18B20":{"Temperature":22.0},"BME280":{"Temperature":21.3,"Humidity":55.7,"Pressure":1002.9},"BH1750":{"Illuminance":12},"TempUnit":"C"}}



```

**To Reproduce**
Put a switch1 on any pin, and the i2c display will turn on or off with that switch
configure it as switch2, same thing will happen
display will follow the highest switch/relay configured
The only way to have display on AND a switch configured that i've found is to use phisical switch as switch1, and add a virtual relay2 somewhere to fool the display so it will follows it.

**Expected behavior**
If i want to turn on or off a display, i think it's better to specify at which relay/switch it has to respond. Right now, it will vary according to other switches configured.

**Comment by arendst** [comment] 2018-10-27 17:51
As designed. You have found a good workaround.

**Comment by ascillato2** [comment] 2018-10-27 18:02
Closing issue as has been answered.

**Closed by ascillato2** 2018-10-27 18:02 UTC
Labels: question

**Comment by Hansolduron** [comment] 2019-01-18 00:12
So where can one know about such typical behaviour ? Looks like a switch no matter what its number can control a relay no matter what its number. Is this documented somewhere on the Wiki. I have been reading and trying to get my Sonoff configured correctly for some month's on and off now.

Thanks,
