### ISSUE TITLE
Sonoff on development build cannot connect to WiFi

### ISSUE THREAD

**Issue by legotheboss** [arendst/Sonoff-Tasmota#3058] opened 2018-06-25 04:24 UTC
**Sonoff fails to detect WiFi network**

_The Sonoff fails to connect to the WiFi network and resorts to the WiFi config tool, which also seems to fail._

- [x] Searched the problem in issues and in the wiki
- [x] Hardware used : Sonoff Basic 
- [x] Provide the output of command ``status 0`` :
```
00:00:00 Project sonoff Sonoff (Topic sonoff, Fallback DVES_45470D, GroupTopic sonoffs) Version 6.0.0a-2_3_0
00:00:00 WIF: Connecting to AP1 WIFINETWORK in mode 11N as sonoff-1XXX...
00:00:07 WIF: Connect failed as AP cannot be reached
00:00:07 WIF: Connecting to WIFINETWORK in mode 11N as sonoff-1XXX...
00:00:14 WIF: Connect failed as AP cannot be reached
00:00:14 WIF: WifiManager active for 3 minutes
00:00:15 HTP: Web server active on sonoff-1XXX with IP address 192.168.4.1
```

**To Reproduce**
1. Clone development repository
2. Open in atom
3. Open user_config file and set WiFi parameters
4. Flash onto Sonoff

**Expected behavior**
Sonoff should boot properly and connect to Wifi

**Temporary Fix**
Using stable 5.14.0 repository allows the sonoff to work properly

**Comment by curzon01** [comment] 2018-06-25 07:02
Be aware changes in user_config.h are taken only for first time on fresh device. This is important to know if you successively use different tests with different user_config on same device.

To force using your user_config changes use command `Reset 1` or `Reset 2` or change _CFG_HOLDER_ (see [CFG_HOLDER explained](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#cfg_holder-explained)).

To be sure that current user_config.h changes are in use, force using it with one of the three methodes above.

**Comment by legotheboss** [comment] 2018-06-25 16:23
@curzon01 Yep, aware of the CFG. I tried on 3 different Sonoffs as well. The latest development folder build on atom does not allow the Sonoff to connect to the Wifi at all. When I open the 5.14 folder, change the CFG so parameters are reset, and flash the Sonoff, all 3 start responding as normal. I even tried issuing the normal WiFi connect commands over serial and had no luck with those either.

**Comment by ascillato** [comment] 2018-06-26 04:36
Hi,

I could not reproduce your issue.

I have 12 sonoffs running last v6.0.0a without any problem.

The user_config.h file is different for the last version.

Please, try to use the default firmware and set the SSID and PASSWORD from the web interface of Tasmota AP.

**Comment by legotheboss** [comment] 2018-06-26 04:45
@ascillato I think the issue I am having has to do with me setting the WiFi failsafe to WIFI_MANAGER, which should create a hotspot for me to connect and properly set the wifi network.

**Comment by ascillato** [comment] 2018-06-26 04:49
I also have wifi_manager as wifi_config on the user_config.h. Then, after I connect Tasmota to my wifi, I change it to wifi_wait. So, if I reset all the config, it will change again to wifi_manager.

**Comment by stefanbode** [comment] 2018-06-26 11:20
Can you check, if you get an improvement by removing the line 
WiFi.persistent(false);   // Solve possible wifi init errors

in support.ini. In my case, this helps to get connected. @arendst: Maybe we see a side effect here. For me the connect works better without this line.

**Comment by ascillato2** [comment] 2018-07-10 09:54
Hi,

Have you managed to solve your issue?

**Comment by amore75** [comment] 2018-07-15 02:47
Having the same issue.  Tried all the suggested fixes and I haven't been able to find anything that works.

**Comment by ascillato2** [comment] 2018-07-25 16:11
Hi,

Please, try last release that have some wifi fixes. Closing issue.

Please, open a new issue with the template complete if you are experiencing problems. thanks

**Closed by ascillato2** 2018-07-25 16:11 UTC
