### ISSUE TITLE
Tasmota esp32 shows error as **'const char HTTP_HEAD []' redeclared as different kind of symbol**

### ISSUE THREAD

**Issue by rulshid** [arendst/Sonoff-Tasmota#3833] opened 2018-09-18 04:40 UTC
hi, i'm using  tasmota in my esp32(with ardino ide 1.8.7), i have downloaded it from  https://github.com/JacekDob/Sonoff-Tasmota
and moved(copy) all the files inside the /lib into my ardino/library folder but compiling the program shows this error 
and i don't know how to solve the issue  please help me ..

_Originally posted by @rulshid in https://github.com/arendst/Sonoff-Tasmota/issue_comments#issuecomment-422252443_

**Comment by Frogmore42** [comment] 2018-09-18 05:28
Since the issue is with code that you downloaded from a different project, you probably should ask the question there.

**Comment by Jason2866** [comment] 2018-09-18 07:53
@rulshid 
Tasmota does not Support ESP32!
You have to make an issue at this project: https://github.com/JacekDob/Sonoff-Tasmota
Plz close this issue.

**Closed** 2018-09-18 11:49 UTC
Labels: invalid
