### ISSUE TITLE
Controlling channels/pwm lines independently/individually with SetOption15 = 1

### ISSUE THREAD

**Issue by mirko** [arendst/Sonoff-Tasmota#6175] opened 2019-08-04 10:11 UTC
Assumption: As far as I remember the old API of controlling lights via PWM commands - SetOption15=OFF - is deprecated. Since I'm having an issue with the new API, which worked with the old one, I allow myself to consider that being a regression.

I use the H801 to control 5 LEDs - not a strip and no colors involved. Just 5 simple plain LEDs which I'd like to dim.
Now, with SetOption=1 I can (almost!) to so, via the individual ChannelX commands. However when I set all 5 channels to 100, 4 is always set to 0.
From my understanding that's due to the logical representation of RGBWxWy, where I can't set Wx and Wy to 100, but have to decide (which makes Wy = 100 -> Wx = 0).

Is there a way to control all 5 LEDs individually with SetOption=1?

**Comment by s-hadinger** [comment] 2019-08-04 10:22
Duplicate of #6134 

Use `SetOption37 128` to allow independent settings of RGB and WW, and use `Channel<x>` to set each PWM value.

If you're adventurous, I have a PR in the works to make it easier to use: https://github.com/s-hadinger/Sonoff-Tasmota/tree/temp_multi_chan

**Comment by ascillato2** [comment] 2019-08-04 15:01
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed by ascillato2** 2019-08-04 15:01 UTC
Labels: duplicated, template missing
