### ISSUE TITLE
WIFI problems after upgrade to Version 6.3.0

### ISSUE THREAD

**Issue by jk2020** [arendst/Sonoff-Tasmota#4254] opened 2018-11-03 07:28 UTC
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Development/Compiler/Upload tools used :
- [x] Hardware used : sonoff basic
- [x] Provide the output of command ``status 0`` :
```
status 0
00:00:55 CMD: status 0
00:00:55 RSL: stat/sonoff01/STATUS = {"Status":{"Module":1,"FriendlyName":["sonoff01"],"Topic":"sonoff01","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:00:55 RSL: stat/sonoff01/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:55","StartupUTC":"","Sleep":0,"BootCount":29,"SaveCount":51,"SaveAddress":"FB000"}}
00:00:55 RSL: stat/sonoff01/STATUS2 = {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018-10-30T17:33:53","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
00:00:55 RSL: stat/sonoff01/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Free VirusFI",""],"TelePeriod":300,"SetOption":["00008009","55818000","00000001"]}}
00:00:55 RSL: stat/sonoff01/STATUS4 = {"StatusMEM":{"ProgramSize":489,"Free":512,"Heap":15,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","000183A0","23B617CE","00003BC0"]}}
00:00:55 RSL: stat/sonoff01/STATUS5 = {"StatusNET":{"Hostname":"sonoff01-6769","IPAddress":"0.0.0.0","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"5C:CF:7F:7A:7A:71","Webserver":2,"WifiConfig":2}}
00:00:55 RSL: stat/sonoff01/STATUS6 = {"StatusMQT":{"MqttHost":"smarthome.jfr.de","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_7A7A71","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:00:55 RSL: stat/sonoff01/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 00:00:55 1970","Local":"Thu Jan 01 00:00:55 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":1,"Sunrise":"07:43","Sunset":"16:03"}}
00:00:55 RSL: stat/sonoff01/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:00:55","Switch1":"ON"}}
00:00:55 RSL: stat/sonoff01/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:00:55","Uptime":"0T00:00:55","Vcc":3.116,"POWER":"ON","Wifi":{"AP":1,"SSId":"Free VirusFI","BSSId":"80:2A:A8:CA:7E:9B","Channel":1,"RSSI":100}}}

```
I have updated two sonoff basic to tasmota Version 6.3.0 and face WIFI connection problems with both devices. If I switch back to Version 6.1.1. or 6.2.1 everything works perfect.

Whereas update on Sonoff Dual R2 with 6.3.3. seems to have no problems

**Comment by wongnam** [comment] 2018-11-03 09:34
try this version 6.3.0.2 for Sonoff basic.

**Comment by GasTurbineMan** [comment] 2018-11-03 12:16
I am facing similar situations with my Sonoff Basics.  All working fine with 6.2.1.16 but when I upgraded a couple OTA with 6.3.0 they would not connect.  I flashed them manually with USB flash device and when I power them up, I can initially connect if I do it in a hurry, but then the radios seem to fade off as I eventually will lose connection.  Tried 6.3.0.1 and 6.3.0.2 and same results.

I will try above .bin as well and continue to monitor this thread.

**Comment by GasTurbineMan** [comment] 2018-11-03 13:05
I was able to perform OTA update to the sonoff-basic.bin you provided above on one of my 2 problem devices and it appears to be working good.  Was not able to do OTA on the other device but did manually flash the device with the sonoff-basic.bin you provided and it too appears to be working ok.

I will add that I typically download the .zip source, edit the user_config.h (now my_user_config.h) file and built the .bin with PlatformIO with for the most part very good success.  I do disable a large number of options to keep my code size down so as to do OTA updates with a single upload. I primarily need MQTT and sensor support for DS18B20's

[user_config - WORKS from 6.2.1.16.h.txt](https://github.com/arendst/Sonoff-Tasmota/files/2544977/user_config.-.WORKS.from.6.2.1.16.h.txt)

[my_user_config - DOES NOT WORK with 6.3.0.2.h.txt](https://github.com/arendst/Sonoff-Tasmota/files/2544978/my_user_config.-.DOES.NOT.WORK.with.6.3.0.2.h.txt)

Attached are my 2 config files.  6.2.1.16 works on all 27 of my devices (all OTA) but I would not get my build for 6.3.0.2 to work on the only 2 devices I tried them on.

I know it is frustrating working with folks like me to don't simply use your provided .bin files, but I do appreciate your help.  Thank you.

**Comment by andrethomas** [comment] 2018-11-03 13:13
The sonoff-basic.bin can be self-compiled by uncommenting the following line in my_user_config.h

`//#define USE_BASIC                                // Create sonoff-basic with no sensors`

There were also changes made to the driver startup with effect from 6.3.0.2 onward so these are also at play in the sonoff-basic.bin which I provided the link for.

**Comment by Doorus** [comment] 2018-11-03 20:44
Hello, i had the same issue. I flashed with 6.3.0.2 and the problems are solved,

Thanx a lot.

**Comment by GasTurbineMan** [comment] 2018-11-03 22:40
@andrethomas 
//#define USE_BASIC // Create sonoff-basic with no sensors

I uncommented out the above line in my_user_config.h as you suggest and compiled in PlatformIO.  I then uploaded OTA to a 3rd Sonoff running great with 6.2.1.16.  The Sonoff works fine on 6.3.0.2 but only problem was that I could not see my DS18B20 temperature sensor that is connected to it.  Assume the sonoff-basic has these disabled? 

I then did another OTA upgrade on this same Sonoff with one of my 6.3.0.2.bin files that previously would not work and it worked on this Sonoff.  No issues, 6.3.0.2 with DS18B20 sensors enabled.

I then tried the same .bin file OTA on a 4th and 5th sonoffs and they have connection issues.  Maybe should have did the sonoff-basic.bin on these 1st and then followed up with my homespun.bin

Will keep trying.

**Comment by andrethomas** [comment] 2018-11-03 23:43
The only difference there is that the ds18b20 is disabled but if you got it working with the normal sonoff.bin then that's also good news because you can try something on the ones which it does not work on.

Try command
sleep 5
and see what happens - if wifi connects you are in the clear.

If not, then self-compile is an option to only enable the specific drivers that you need but still define AP_SLEEP 5 in the configuration.

Remember after flashing with a previously configured device you will need to perform command reset 4 to restore to defaults stored in the user_config file but reset 4 will retain your wifi settings so only the rest will need to be reconfigured.

**Comment by jk2020** [comment] 2018-11-04 07:00
> 
> 
> Hello, i had the same issue. I flashed with 6.3.0.2 (http://thehackbox.org/tasmota/sonoff-basic.bin).
> The problems are solved,
> 
> Thanx a lot.

same here; seems to work with Version 6.3.0.2 for sonoff basic

**Comment by andrethomas2** [comment] 2018-11-04 11:59
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Closed by andrethomas2** 2018-11-04 11:59 UTC
Labels: awaiting for feedback, troubleshooting

**Comment by toto79** [comment] 2018-11-09 16:33
same problem here with a Sonoff S20.
V6.1.1 no problems (signal strength ~50%), 
with V6.3.0. and V6.3.0.5 of sonoff-sensors.bin Wifi seems to sleep after some seconds, but shows a signal strength of 60%, console log...reconecting after 10 sec

sonoff-basic.bin is no option, because this device transmits data of a DHT22 and a DS18B20

**Comment by ascillato** [comment] 2018-11-09 16:41
> sonoff-basic.bin is no option, because this device transmits data of a DHT22 and a DS18B20

So, you need to compile a version with just the features you want. See the wiki for instructions

**Comment by marcohorstmann** [comment] 2018-11-17 23:03
I downgraded to 6.1.1 and the basic works. The 6.3.0 build against commit  61b8586 didn't resolved my issue.

**Comment by ascillato** [comment] 2018-11-17 23:11
Please, use the latest version from development branch at http://thehackbox.org/tasmota/sonoff-basic.bin

Thanks

**Comment by marcohorstmann** [comment] 2018-11-17 23:25
@ascillato I've downloaded exact the version you refered to, but also is unstable at my basic.

**Comment by ascillato** [comment] 2018-11-17 23:55
You said that you have downloaded 6.3.0 but the latest is 6.3.0.8

The latest works fine on sonoff basics.

**Comment by toto79** [comment] 2018-11-18 13:51
> @ascillato I've downloaded exact the version you refered to, but also is unstable at my basic.

Sonoff Basic 6.3.0.8 with console command `sleep 5` works for me, but it‘s very tricky to sind this command within the short uptime... so my other sonoffs stay at 6.2.1 without any problems.

**Comment by GasTurbineMan** [comment] 2018-11-18 14:30
Enter the console command Sleep 5 while still operating on the older version bin (before you upgrade to the newer bin).  Then you should be able to complete your OTA upgrade to 6.3.0.8 and have Sonoff be stable when it restarts.

**Comment by marcohorstmann** [comment] 2018-11-21 10:55
Sonoff basic 6.3.0.10 with sleep 5 works fine for me. since yesterday both modules are stable.

**Comment by andrethomas** [comment] 2018-11-21 17:47
From 6.3.0.10 you should actually not need sleep at all - have you tested 6.3.0.10 without sleep on a sonoff basic? would be curious to know the result. Thanks

**Comment by marcohorstmann** [comment] 2018-11-21 19:02
@andrethomas no, I had set sleep to 5 on all devices and will leave it for now. I use the 3 basics for my Christmas lights in my garden. In the moment i have no time for troubleshooting. Too much work, homework etc.

**Comment by toto79** [comment] 2018-11-21 19:04
> From 6.3.0.10 you should actually not need sleep at all - have you tested 6.3.0.10 without sleep on a sonoff basic? would be curious to know the result. Thanks

Means this for all Sonoff-*.bin or only for Sonoff-Basic.bin?

( i think the referenced issue  and the power support suggestion isn’t our problem... I have the same issue with 2 Sonoff s20 and only tasmota 6.3... (espeasy has no issues like this for me)

**Comment by marcohorstmann** [comment] 2018-11-21 19:09
@toto79 my 10x s20 with 6.3.0 had not shown any problems when I preconfigured them. Most of my S20 lay in my office and waiting for installation of in-house Christmas lights. Die basics showed imminently another behavior then the S20

**Comment by andrethomas** [comment] 2018-11-21 20:03
> Means this for all Sonoff-*.bin or only for Sonoff-Basic.bin?

sonoff.bin should work on a sonoff basic now - you are still welcome to use sonoff-basic.bin on a sonoff basic but for other devices we always recommend the original sonoff.bin firmware.

Depending on the outcome of some tests the sonoff-basic.bin may be discontinued if the problems are confirmed solved.

Since these are Sonoff 1x/2x devices I cannot confirm if it is the same problem, but the latest dev build is running fine on all 63 of my Tasmota driven devices. Not all use sonoff.bin in its current form though, some of the devices are scratch built from ESP-07 and ESP-12 modules so they have very specific drivers enabled based on what they are doing.

So if there's still an isolated problem on the S10 and S20 then this is something not related to power or cpu usage so we will need to figure out what the cause of this is.

The main reason we seem to have gotten to the core issue on the sonoff basic is because both @arendst and I have "picky" sonoff basic's R1's and a known not to work Sonoff Basic R2 was sent to @Jason2866 by @raymajor and we did some extensive testing with different approaches to get it running smoothly.

So perhaps something similar would be needed for the S20, although @Jason2866 has a S20 and has not seen the same problems we had with the sonoff basics'

**Comment by abarnesy** [comment] 2018-11-22 11:54
I had an S20 and a TH16 side by size with 6.3.0.0. The TH kept losing the wifi.
Upgraded OTA to http://thehackbox.org/tasmota/sonoff.bin 6.3.0.11 and it seems to be a lot more stable.

**Comment by andrethomas** [comment] 2018-11-22 12:13
@abarnesy That's good to hear - check back at http://thehackbox.org/tasmota/ in about 10 minutes or so... 6.3.0.12 (build d71ae77) adds some additional optimizations and is busy building as I am typing this.

**Comment by abarnesy** [comment] 2018-11-23 10:40
Spoke to soon. My devices with weaker wifi 30-40% are intermittently dropping out and going into AP mode.

**Comment by wongnam** [comment] 2018-11-23 10:46
How to became AP mode, Tasmota default Wifi setting is  Wait or Retry. Do you set it to other mode?

**Comment by wongnam** [comment] 2018-11-23 13:59
Recommend use core version 2.3.0 for Wifi stable.
As my experience that the core version 2.4.2 is unstable for some sonoff device, i don’t know why, some sonoff device works some doesn’t work. i am still isolating it.

**Comment by abarnesy** [comment] 2018-12-03 11:43
6.3.0.12 has been better, but sometimes will not get a connection first go after a power cut.
I have also tried 6.3.0 and 6.3.0.15 on a new Pow R2 and it is stuck in a constant reboot loop. I was not able to get to saving the basic setting as Pow R2 model, so wonder if that had something to do with it.
Wondering if trying 6.1.x or 6.2.x is a better bet at this point?

**Comment by Jason2866** [comment] 2018-12-03 12:04
Start from scratch. Erase Flash with esptool. Flash latest dev version http://thehackbox.org/tasmota/sonoff.bin
If there are fragments left in flash it can generate issues.
For stable wifi i do recommend core 2.3.0

**Comment by andrethomas** [comment] 2018-12-03 12:15
After flashing 6.3.0.15 please remember to verify that sleep is set to 50 or higher.

**Comment by wongnam** [comment] 2018-12-03 12:18
@andrethomas  thanks for remind. i have just flash and saw Sleep value is 50.
```
19:13:13 MQT: tele/newswitch/STATE = {"Time":"2018-12-03T19:13:13","Uptime":"0T00:05:16","Vcc":3.390,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Multimedia Wi-Fi Network","BSSId":"B0:C7:45:36:85:E0","Channel":6,"RSSI":100}}
```

**Comment by andrethomas** [comment] 2018-12-03 12:31
Yes, from 6.3.0.15 setoption36 functionality was merged with sleep command.

So sleep command works the same as it did before but defaults to dynamic sleep (what we had with setoption36)

You have the option to switch back to traditional/normal sleep using SetOption60 as documented [in the wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Dynamic%20Sleep) so to make the transition from previous 6.3.0.10 and later to 6.3.0.15 we force sleep to a default value of 50 and it defaults with dynamic sleep enabled.

A complete erase and re flash with 6.3.0.15 or higher will also result in a default of sleep 50 with Dynamic Sleep enabled by default.

**Comment by abarnesy** [comment] 2018-12-03 12:32
I shouldn't do these things late at night. I think i OTA flashed 6.3.0.15 and it must have had remnants of old config. Seems to be ok after a full erase and re-flash, thanks.

**Comment by Jason2866** [comment] 2018-12-03 15:35
@wongnam 
For me Hue Emulation works in 2.3.0 and 2.4.2 without an issue.
In 2.4.2. you have to modify parsing.cpp in core....
Here is the patched one: 
[Parsing.zip](https://github.com/arendst/Sonoff-Tasmota/files/2640110/Parsing.zip)

**Comment by andrethomas** [comment] 2018-12-03 15:50
@Jason2866 Thanks for the replacement Parsing.cpp - I've added it to the build script for the pre-compiled development binaries so that will be in effect when the next auto build takes place at the top of the hour.

**Comment by andrethomas** [comment] 2018-12-03 16:24
@wongnam @Jason2866 The pre-compiled development binaries with core 2.4.2 at http://thehackbox.org/tasmota/020402/ should work now with Hue Emulation as your Parsing.cpp patch has been applied to the build script. I forced a rebuild so the files that are there now are ready for testing if you like.

**Comment by wongnam** [comment] 2018-12-04 07:00
> @wongnam
> For me Hue Emulation works in 2.3.0 and 2.4.2 without an issue.
> In 2.4.2. you have to modify parsing.cpp in core....
> Here is the patched one:
> [Parsing.zip](https://github.com/arendst/Sonoff-Tasmota/files/2640110/Parsing.zip)

@Jason2866 The workaround parsing.ccp worked as a charm, it's the same workaround method for core 2.4.0 before but a little changed in the code line#. Thanks.

**Comment by jcalderon71** [comment] 2018-12-07 22:32
Hi all. I need some help I’m new with the flashing process. Yesterday I upgrade my sonoff basic that came with 5.9 to 6.3.0 after the upgrade OTA the green led is flashing and I cannot connect to WiFi. Question is how I can put on pairing mode to flash it back to 6.2.1

**Comment by meingraham** [comment] 2018-12-07 22:39
@jcalderon71 6.3.0 master has a few known Wi-Fi connectivity issues. Use the latest development version source code or grab a pre-compiled binary here: http://thehackbox.org/tasmota/020402/

**Comment by jcalderon71** [comment] 2018-12-07 22:51
@meingraham Ok thanks, but how  do i put the sonoff on pairing mode again? if I pressed the button for 7sec doesn't go to pairing stage anymore? the 1st upgrade was OTA

**Comment by meingraham** [comment] 2018-12-07 23:39
Did you flash the new firmware? Once you have the latest firmware on your device, these button sequences tell you how to put the device into the appropriate mode for pairing and configuration: https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage

**Comment by Jason2866** [comment] 2018-12-08 09:39
@jcalderon71 
Bad news: If the device isnt reachable via web or mqtt you wont be able to do OTA upgrade.
Good news: Flashing latest development firmware via seriall will bring back your device to life

**Comment by jcalderon71** [comment] 2018-12-10 22:34
Ok thank you for the information


Best regards
