### ISSUE TITLE
Firmware 6.6.0 AND Amazon Echo Dot Gen. 2 AND WeMo Emulation = no new devices found

### ISSUE THREAD

**Issue by M4APger** [arendst/Sonoff-Tasmota#6086] opened 2019-07-13 08:38 UTC
Release 6.5.0 works fine

Release 6.6.0:
- Emulation: Belkin WeMo 
- 2x Amazon Echo Dot Gen. 2
no new device found - (old devices works fine)

test environment:
AVM FritzBox 7590 - 7.11
2x Amazon Echo Dot Gen. 2
3x Sonoff S20
1x Sonoff Touch
1x Sonoff Pow
1x Sonoff TH16
... and more

no working:
- latest release 6.6.0 (core 2.3.0 / 2.4.2 / 2.5.2)
- development release 6.6.0.1 (core 2.3.0 / 2.4.2 / 2.5.2) Build 2019-07-12T10:10:06

flashing back up 6.5.0 works fine !!!

Sorry ... my english is not the yellow of the egg!

More infos in German:
https://forum.creationx.de/forum/index.php?thread/2013-tasmota-release-6-6-0/&postID=25076#post25076

----------------------------------------------------------------------------------------------------------

<This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
  
<Please DO NOT OPEN AN ISSUE:>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### BUG DESCRIPTION
_A clear and concise description of what the bug is._

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Device used (i.e. Sonoff Basic) : _____
- [ ] Tasmota binary firmware version number used : ____ / (pre-compiled or self-compiled ?)
- [ ] Development IDE - Compiler / Upload tools used : ____ / ____
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:


```
- [ ] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ihavenonick** [comment] 2019-07-13 08:54
same here, with Dot 3 no Problem, but with Dot 2 no new detection after removing the device

**Comment by Jason2866** [comment] 2019-07-13 08:55
WeMo Emu is known not working reliable since a while. Use HueEmulation instead.
HueEmulation is better anyway because there is feedbaxk back to sender that command is done.

**Comment by ihavenonick** [comment] 2019-07-13 09:14
No good news, because i don't like the slider and color bar in Alexa if i use only a simple switch and the problems with HUE EMU in the past was not funy to.
Also i had never a Problem with WeMo EMU without a feedback to sender.

I think i will use Node-Red WeMo for connection to Alexa.

**Comment by M4APger** [comment] 2019-07-13 10:26
That's really not good news!
the fact is:
WeMo is for switches
Hue is for lights

**Comment by s-hadinger** [comment] 2019-07-13 12:11
Ha ha! I finally understand why we had mixed reports about WeMo emulation. It has always worked perfectly for me but I have multiple Echo device at home.

With a single Echo Dot 2nd gen, I do confirm WeMo emulation does not work (6.6.0). Log below:

```
13:02:45 HTP: Console
13:02:48 UDP: Packet (122)
13:02:48 UDP: Packet (122)
13:02:48 UDP: Packet (107)
13:02:49 UDP: Packet (107)
13:02:50 UPP: WeMo Type 1, Response sent to 192.168.1.25:50000
13:02:51 WIF: Checking connection…
```

Now as soon as I switch on my Echo Spot, it suddenly works. Log:

```
13:05:51 WIF: Connected
13:05:59 UDP: Packet (94)
13:05:59 UDP: Packet (101)
13:05:59 UDP: Packet (94)
13:05:59 UDP: Packet (101)
13:05:59 UDP: Packet (94)
13:05:59 UDP: Packet (101)
13:05:59 UDP: Packet (107)
13:05:59 UDP: Packet (107)
13:05:59 UDP: Packet (122)
13:05:59 UDP: Packet (122)
13:06:00 UPP: WeMo Type 2, Response sent to 192.168.1.43:50000
13:06:01 HTP: WeMo setup
13:06:01 HTP: WeMo basic event
13:06:01 HTP: WeMo basic event
13:06:03 HTP: WeMo basic event
```

I'll try to dig about the difference between WeMo Type 1 and WeMo Type 2. What's still surprising is that I'm not aware of any significant change in WeMo code between 6.5.0 and 6.6.0.

Time for debug! Thanks @M4APger for reporting this bug.

**Comment by s-hadinger** [comment] 2019-07-13 12:39
I found a difference between 6.5.0 and 6.6.0:

6.6.0:
```
const char URN_BELKIN_DEVICE[] PROGMEM = "urn:belkin:device:**";
```

6.5.0:
```
response.replace("{r3", F("urn:Belkin:device:**"));
```

So it looks like a capitalization error and should be: 
```
const char URN_BELKIN_DEVICE[] PROGMEM = "urn:Belkin:device:**";
```

I don't have time to test now...

**Comment by arendst** [comment] 2019-07-13 12:40
I will push an update with this fix now.

**Comment by s-hadinger** [comment] 2019-07-13 13:17
We need to test it before. This string is used in two locations. So we may need two different strings, one with small b one with Capital B. 

And it's maybe not the problem at all.

**Comment by M4APger** [comment] 2019-07-13 13:40
My test socket is ready. Is the bug fix in the latest development version?
20190712 14:02 GMT + 2
I could test these then!

**Comment by arendst** [comment] 2019-07-13 13:42
Nope. Wait another hour for it to be available.

**Comment by s-hadinger** [comment] 2019-07-13 14:31
Confirmed to work, but we do need 2 strings.
I'm pushing the PR right now.

**Comment by s-hadinger** [comment] 2019-07-13 14:35
@M4APger Fix is here if you want to test before it is merged into development: 02ee16c3dcec012bd374d3b8faea60d50a9de675

**Comment by ascillato2** [comment] 2019-07-13 14:38
Closing this issue as it is solved.

Thanks everyone for working on this :+1:

**Closed by ascillato2** 2019-07-13 14:38 UTC
Labels: bug, fixed

**Comment by s-hadinger** [comment] 2019-07-13 14:46
There one glitch you need to know, if the WeMo device was discovered by a newer echo device, it cannot be controlled via an echo 2G. You need to remove the device and redo a discovery.

But if all you have are echo dot 2G, then there's no issue.

**Comment by M4APger** [comment] 2019-07-13 17:46
Program Version | 6.6.0.1(7e20579-classic)
Build Date & Time | 2019-07-13T19:04:10
Core/SDK Version | 2_3_0/1.5.3(aec24ac9)

Test Ok ... 
Development BIN 20190713 19:04 GMT+2

thx

**Comment by oywino** [comment] 2019-09-18 06:57
Hi all, 
I have flashed my Sonoff Basic successfully with Tasmota 6.6.0 and got it up'n'running on my WLAN.
Then I changed its configuration to; Disable MQTT and enable WeMo emaulation, hpoing that I could see the switch in my Home Assistant 0.98.2
The integration shows up ok, but no device is added/visible.
Then I changed to Hue Bridge emulation, but that resulted in nothing at all.
I both cases, I manually added the host IP to _configuration.yaml_
What am I missing here?

**Comment by Jason2866** [comment] 2019-09-18 09:11
@oywino  HueEmulation in Tasmota is designed for the use with Alexa.
It CAN work for other systems.

**Comment by oywino** [comment] 2019-09-18 09:20
@Jason2866  This is the error message I get from HA ;

`Log Details (ERROR)
Wed Sep 18 2019 08:46:11 GMT+0200 (Central European Summer Time)
Unknown error connecting with Hue bridge at 192.168.0.21
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/config_flow.py", line 207, in async_step_import
    bridge = await get_bridge(self.hass, host, username)
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 171, in get_bridge
    await bridge.initialize()
  File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 45, in initialize
    self.config = Config(result['config'], self.request)
TypeError: list indices must be integers or slices, not str`

**Comment by Jason2866** [comment] 2019-09-18 09:25
As i said before, no support for other devices'/ software. 
HueEmulation is ONLY for Alexa.

**Comment by s-hadinger** [comment] 2019-09-18 09:40
This is an HA issue. Please direct it to the HA project. If solving it requires simple changes in Tasmota we may do it. But diagnosis must be done by HA first.

**Comment by oywino** [comment] 2019-09-18 18:36
@Jason2866 & @s-hadinger  OK guys - thanks for taking the time to reply.
One last question: Where can I find a user guide that will explain in detail all the various settings, configs and template options in the Tasmota Web front end?

**Comment by meingraham** [comment] 2019-09-18 18:54
@oywino Click the `Wiki` tab at the top of the page.

**Comment by Makk1983** [comment] 2019-10-13 09:47
Hi, I'm starting to experiment with Alexa now and I wanted to integrate my sonoff tasmota 6.6.0, I enabled the Belkin WeMo emulation, I tried to add a new device to alexa but found nothing, I tried to change emulation again in Hue Bridge but nothing, then reading on this forum I installed version 6.5.0 but nothing does not work, may be due to the fact that I have no device (DOT, Echo etc.) but only the app on the smartphone?

**Comment by s-hadinger** [comment] 2019-10-13 13:04
Alexa Hue integration requires a physical Alexa device. The app alone is not enough.
