### ISSUE TITLE
VS Code con Ubuntu 19.04 - error: forward declaration of 'struct rst_info'

### ISSUE THREAD

**Issue by snakuzzo** [arendst/Sonoff-Tasmota#6721] opened 2019-10-22 21:19 UTC
### ISSUE DESCRIPTION - TROUBLESHOOTING
Error compiling 6.6 on VS Code
  

### REQUESTED INFORMATION

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [x] Tasmota binary firmware version number used: 6.6
  - [ ] Pre-compiled
  - [x] Self-compiled
    - [x] IDE / Compiler used: VS Code
- [ ] Flashing tools used: _____

- [x] Provide the output of the Console log output when you experience your issue; if applicable:
```
Console output here:
  
Processing sonoff (platform: espressif8266@1.5.0; framework: arduino; board: esp01_1m)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 1.5.0 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: toolchain-xtensa 1.40802.0 (4.8.2), framework-arduinoespressif8266 1.20300.1 (2.3.0), tool-esptool 1.409.0 (4.9)
Converting sonoff.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 62 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <BearSSL> 0.6
|-- <Adafruit CCS811 Library> 1.0.0
|   |-- <Wire> 1.0
|-- <Adafruit MAX31865 library> 1.0.1
|   |-- <SPI> 1.0
|-- <Adafruit SGP30 Sensor> 1.0.3
|   |-- <Wire> 1.0
|-- <I2Cdevlib-Core>
|   |-- <Wire> 1.0
|-- <I2Cdevlib-MPU6050>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <Mutichannel_Gas_Sensor> 0.0.1
|   |-- <Wire> 1.0
|-- <VL53L0X> 1.0.2
|   |-- <Wire> 1.0
|-- <C2Programmer> 1.0.0
|-- <A4988_Stepper> 0.0.1
|-- <I2Cdevlib-ADS1115>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <Adafruit GFX Library> 1.5.6
|   |-- <SPI> 1.0
|-- <Adafruit ILI9341> 1.2.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <Adafruit LED Backpack Library> 1.1.6
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <Adafruit_SH1106-gemu-1.0>
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <Adafruit SSD1306> 1.3.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|-- <ArduinoHexParse> 0.0.1
|-- <ArduinoJson> 5.13.4
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266HTTPClient> 1.1
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266httpUpdate> 1.1
|   |-- <ESP8266HTTPClient> 1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <AT24C256>
|   |-- <Wire> 1.0
|-- <FT6236-gemu-1.0>
|   |-- <Wire> 1.0
|-- <FrogmoreScd30>
|   |-- <Wire> 1.0
|-- <ILI9488> 1.0.2
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <IRremoteESP8266> 2.6.5
|-- <LinkedList>
|-- <LiquidCrystal_I2C>
|   |-- <Wire> 1.0
|-- <NeoPixelBus> 2.5.0
|   |-- <SPI> 1.0
|-- <NewPing> 1.9.1
|-- <PubSubClient> 2.7
|-- <RA8876> 1.0.2
|   |-- <SPI> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|-- <rc-switch> 2.6.2
|-- <SD(esp8266)> 1.0.5
|   |-- <SPI> 1.0
|-- <SPI> 1.0
|-- <SSD3115> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <EspSoftwareSerial>
|-- <TasmotaModbus> 1.2.0
|   |-- <TasmotaSerial> 2.4.1
|-- <TasmotaSerial> 2.4.1
|-- <Ticker> 1.0
|-- <Joba_Tsl2561> 2.0.10
|   |-- <Wire> 1.0
|-- <Wire> 1.0
|-- <base64> 1.1.1
|-- <BME680_driver-bme680_v3.5.9>
|-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <ESP KNX IP Library> 0.5.2
|   |-- <EEPROM> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
Retrieved `.pioenvs/sonoff/src/Parsing.cpp.o' from cache
Retrieved `.pioenvs/sonoff/src/StackThunk_light.cpp.o' from cache
Retrieved `.pioenvs/sonoff/src/WiFiClientSecureLightBearSSL.cpp.o' from cache
Retrieved `.pioenvs/sonoff/src/core_esp8266_timer.c.o' from cache
Retrieved `.pioenvs/sonoff/src/core_esp8266_wiring_digital.c.o' from cache
Retrieved `.pioenvs/sonoff/src/core_esp8266_wiring_pwm.c.o' from cache
Compiling .pioenvs/sonoff/src/sonoff.ino.cpp.o
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/ESP8266WiFi.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/ESP8266WiFiAP.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/ESP8266WiFiMulti.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/ESP8266WiFiSTA.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/ESP8266WiFiScan.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/WiFiClient.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/WiFiClientSecure.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/WiFiServer.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib049/ESP8266WiFi/WiFiUdp.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib4d2/ESP8266WebServer/Parsing.cpp.o' from cache
Retrieved `.pioenvs/sonoff/lib4d2/ESP8266WebServer/ESP8266WebServer.cpp.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/aead/ccm.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/aead/eax.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/aead/gcm.c.o' from cache
Retrieved `.pioenvs/sonoff/lib4d2/libESP8266WebServer.a' from cache
Retrieved `.pioenvs/sonoff/lib049/libESP8266WiFi.a' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/ccopy.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/dec16be.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/dec16le.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/dec32be.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/dec32le.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/dec64be.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/dec64le.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/enc16be.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/enc16le.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/enc32be.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/enc32le.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/enc64be.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/enc64le.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/pemdec.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/codec/pemenc.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_all_m15.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_c25519_i15.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_curve25519.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_default.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_keygen.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_p256_m15.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_prime_i15.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_pubkey.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_secp256r1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_secp384r1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ec_secp521r1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_atr.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_default_sign_asn1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_default_sign_raw.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_default_vrfy_asn1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_default_vrfy_raw.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_i15_bits.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_i15_sign_asn1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_i15_sign_raw.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_i15_vrfy_asn1.c.o' from cache
/home/snakuzzo/Sonoff-Tasmota/sonoff/sonoff.ino: In function 'void setup()':
/home/snakuzzo/Sonoff-Tasmota/sonoff/sonoff.ino:1572:19: error: invalid use of incomplete type 'struct rst_info'
     if ((resetInfo.reason == REASON_DEFAULT_RST) || (resetInfo.reason == REASON_EXT_SYS_RST)) {
                   ^
In file included from /home/snakuzzo/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:246:0,
                 from /tmp/tmpj2cngw3g:1:
/home/snakuzzo/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/Esp.h:142:16: error: forward declaration of 'struct rst_info'
         struct rst_info * getResetInfoPtr();
                ^
/home/snakuzzo/Sonoff-Tasmota/sonoff/sonoff.ino:1572:30: error: 'REASON_DEFAULT_RST' was not declared in this scope
     if ((resetInfo.reason == REASON_DEFAULT_RST) || (resetInfo.reason == REASON_EXT_SYS_RST)) {
                              ^
/home/snakuzzo/Sonoff-Tasmota/sonoff/sonoff.ino:1572:63: error: invalid use of incomplete type 'struct rst_info'
     if ((resetInfo.reason == REASON_DEFAULT_RST) || (resetInfo.reason == REASON_EXT_SYS_RST)) {
                                                               ^
In file included from /home/snakuzzo/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:246:0,
                 from /tmp/tmpj2cngw3g:1:
/home/snakuzzo/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/Esp.h:142:16: error: forward declaration of 'struct rst_info'
         struct rst_info * getResetInfoPtr();
                ^
/home/snakuzzo/Sonoff-Tasmota/sonoff/sonoff.ino:1572:74: error: 'REASON_EXT_SYS_RST' was not declared in this scope
     if ((resetInfo.reason == REASON_DEFAULT_RST) || (resetInfo.reason == REASON_EXT_SYS_RST)) {
                                                                          ^
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_i15_vrfy_raw.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ec/ecdsa_rta.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/dig_oid.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/dig_size.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/ghash_ctmul.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/ghash_ctmul32.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/ghash_ctmul64.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/ghash_pclmul.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/md5.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/md5sha1.c.o' from cache
/home/snakuzzo/Sonoff-Tasmota/sonoff/support_wifi.ino: In function 'void WifiDisconnect()':
/home/snakuzzo/Sonoff-Tasmota/sonoff/support_wifi.ino:563:27: error: 'wifi_station_disconnect' was not declared in this scope
   wifi_station_disconnect();  // this will store empty ssid/wpa into sdk storage
                           ^
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/mgf1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/multihash.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/sha1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/sha2big.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/hash/sha2small.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_add.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_bitlen.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_decmod.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_decode.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_decred.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_encode.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_fmont.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_iszero.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_moddiv.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_modpow.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_modpow2.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_montmul.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_mulacc.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_muladd.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_ninv15.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_reduce.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_rshift.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_sub.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/int/i15_tmont.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/kdf/hkdf.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/kdf/shake.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/mac/hmac.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/mac/hmac_ct.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rand/aesctr_drbg.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rand/hmac_drbg.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rand/sysrng.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_keygen.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_modulus.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_oaep_decrypt.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_oaep_encrypt.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_pkcs1_sign.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_pkcs1_vrfy.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_priv.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_privexp.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_pss_sign.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_pss_vrfy.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_pub.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_default_pubexp.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_keygen.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_modulus.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_oaep_decrypt.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_oaep_encrypt.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_pkcs1_sign.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_pkcs1_vrfy.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_priv.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_privexp.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_pss_sign.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_pss_vrfy.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_pub.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_i15_pubexp.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_oaep_pad.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_oaep_unpad.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_pkcs1_sig_pad.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_pkcs1_sig_unpad.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_pss_sig_pad.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_pss_sig_unpad.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/rsa/rsa_ssl_decrypt.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/settings.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/prf.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/prf_md5sha1.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/prf_sha256.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/prf_sha384.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_ccert_single_ec.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_ccert_single_rsa.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_client.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_client_default_rsapub.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_client_full.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_aescbc.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_aesccm.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_aesgcm.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_chapol.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_descbc.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_ec.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_ecdsa.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_engine_default_rsavrfy.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_hashes.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_hs_client.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_hs_server.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_io.c.o' from cache
Retrieved `.pioenvs/sonoff/liba31/bearssl-esp8266/ssl/ssl_keyexport.c.o' from cache
*** [.pioenvs/sonoff/src/sonoff.ino.cpp.o] Error 1
==================================================================== [FAILED] Took 4.85 seconds ====================================================================

Environment      Status    Duration
---------------  --------  ------------
sonoff           FAILED    00:00:04.848
sonoff-minimal   IGNORED
sonoff-basic     IGNORED
sonoff-knx       IGNORED
sonoff-sensors   IGNORED
sonoff-display   IGNORED
sonoff-ir        IGNORED
sonoff-ircustom  IGNORED
sonoff-BG        IGNORED
sonoff-BR        IGNORED
sonoff-CN        IGNORED
sonoff-CZ        IGNORED
sonoff-DE        IGNORED
sonoff-ES        IGNORED
sonoff-FR        IGNORED
sonoff-GR        IGNORED
sonoff-HE        IGNORED
sonoff-HU        IGNORED
sonoff-IT        IGNORED
sonoff-KO        IGNORED
sonoff-NL        IGNORED
sonoff-PL        IGNORED
sonoff-PT        IGNORED
sonoff-RU        IGNORED
sonoff-SE        IGNORED
sonoff-SK        IGNORED
sonoff-TR        IGNORED
sonoff-TW        IGNORED
sonoff-UK        IGNORED
============================================================== 1 failed, 0 succeeded in 00:00:04.848 ==============================================================
The terminal process terminated with exit code: 1
```

**Comment by meingraham** [comment] 2019-10-22 21:25
Does 6.6.0.21 compile OK?

As this is a question regarding compilation (see original Issue template), please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by snakuzzo** [comment] 2019-10-22 21:28
I've cloned the project few minutes ago...and compilation is ok just with default core...using core 2.3.0 I've got errors

**Closed** 2019-10-22 22:23 UTC

**Comment by snakuzzo** [comment] 2019-10-22 22:32
As told me on discord chat, 2.3.0 is no longer supproted :(

**Comment by arendst** [comment] 2019-10-23 09:25
Most of the current version is still supported on core 2.3.0

This issue is caused by me tidying up too much. I will restore the cause after which you must be able to compile with core 2.3.0 again now.
