### ISSUE TITLE
Problem Flashing sonoff pow r2 v2.0

### ISSUE THREAD

**Issue by woudenbe** [arendst/Sonoff-Tasmota#4587] opened 2018-12-11 13:50 UTC
I managed to flash th16, basic r2 but the pow r2 v2.0 with date 2018-06-11 i cant get flashed.

I have tried with PC, with raspberry, with pull up resistor between 3.3 and rx none of them worked.

**Comment by arendst** [comment] 2018-12-11 13:52
Pls provide some pictures of the Pow PCA

**Comment by woudenbe** [comment] 2018-12-11 14:02
![20181211_145945](https://user-images.githubusercontent.com/45719715/49805531-9e9df680-fd55-11e8-906a-59173a6d1cad.jpg)
![20181211_145905](https://user-images.githubusercontent.com/45719715/49805546-a9588b80-fd55-11e8-9656-36b0ae85f082.jpg)

**Comment by woudenbe** [comment] 2018-12-11 14:03
![20181211_145928](https://user-images.githubusercontent.com/45719715/49805622-d60ca300-fd55-11e8-9216-410fff661624.jpg)
![20181211_145938](https://user-images.githubusercontent.com/45719715/49805623-d60ca300-fd55-11e8-9c87-d66f9e157800.jpg)

**Comment by ascillato2** [comment] 2018-12-11 14:40
@woudenbe 

Can you check with a DMM if the button is indeed connected to GPIO0 ?

Are you pushing the button before powering up the POW with your USB ?

**Comment by woudenbe** [comment] 2018-12-11 14:44
Hi ascilato2

I have not checked with DMM but will check.

I have even connected gpio0 with a wire to ground.

Yes gpio0 connector to ground before powering up.

I saw pull up resistor mentioned as a possible solution for similar issue.

**Comment by woudenbe** [comment] 2018-12-11 14:50
just checked with DMM, and yes button connects the GPIO 0 to GND.

**Comment by ascillato** [comment] 2018-12-11 14:54
Ok, so instead of using a wire, please try keeping the button pressed before and during the flashing process.

**Comment by woudenbe** [comment] 2018-12-11 15:12
![20181211_160714](https://user-images.githubusercontent.com/45719715/49809436-2a685080-fd5f-11e8-85a8-f7d12c67a1aa.jpg)
![20181211_160924](https://user-images.githubusercontent.com/45719715/49809477-4b30a600-fd5f-11e8-9e39-39e1d36be43c.jpg)

VCC = 3.264 Vdc
tried with 1 sec press
2 sec press
press until flash
press during flash

all the time same result:

![20181211_160850](https://user-images.githubusercontent.com/45719715/49809471-453ac500-fd5f-11e8-858f-c1837d7aa953.jpg)

**Comment by ascillato** [comment] 2018-12-11 15:16
your connections seems ok.

the stock firmware is working fine?

**Comment by ascillato** [comment] 2018-12-11 16:58
From your photos, seems that the issue is a cable that is not making contact.

Could you test all your wires?

I have the same POW and the flashing was fine. Nothing weird. I did just as the wiki explains.

**Comment by woudenbe** [comment] 2018-12-11 17:06
I will check later tonight and update. Thanks for the tip

**Comment by woudenbe** [comment] 2018-12-11 18:14
all cables correct and also connected (measured on pcb side)

**Comment by jziolkowski** [comment] 2018-12-11 19:18
Did you change all the required settings to enable serial port on Rpi3?

https://elinux.org/RPi_Serial_Connection

**Comment by andrethomas** [comment] 2018-12-11 19:19
Also, test the serial interface with termite by connecting a dupont wire from tx to rx on the pi - whatever you type/send should be returned on the screen

**Comment by Jason2866** [comment] 2018-12-11 19:48
Out of ideas...
If i where you i would try a standard USB serial converter with a CH340 chip

**Comment by woudenbe** [comment] 2018-12-11 20:40
i flashed the other sonoff devices in same config...   completely puzzled here. it seems ti be teh new version of the POW R2 that is causing the issue. i have 5 and none of them working....

i have tried with FT231X
i have tried raspberry pi 3b+ (with correct settings)

i will try LH2303HX with an old PC in windows 7

if this will not work i need to wait for delivery (new FTDI) next week

i realy suspect the pow R2 v2.0 to be the issue here and i have FIVE !!  all behaving same

**Comment by ascillato** [comment] 2018-12-11 20:43
May be the measurement MCU is interfering in your flashing ?

**Comment by Jason2866** [comment] 2018-12-11 20:43
Have you measured direct on ESP chip if pressing button really is grounding GPIO 0?

**Comment by woudenbe** [comment] 2018-12-11 21:01
just tried PL2303HX with windows 7 and it worked. now try the other ones :-)

**Comment by woudenbe** [comment] 2018-12-11 21:02
first need to get wifi working :-)

**Comment by ascillato** [comment] 2018-12-11 21:04
Great!!!

So your issue was the Raspberry? Now your issue is solved?

**Comment by woudenbe** [comment] 2018-12-11 21:08
well not sure, as rasp berry & ft231X  gave same problem

**Comment by woudenbe** [comment] 2018-12-11 21:08
seems to work now. Thanks for all the help guys !

**Comment by ascillato** [comment] 2018-12-11 21:09
Great!!!

Nice to know

Please, close this issue. Thanks

**Closed** 2018-12-11 21:12 UTC
Labels: awaiting for feedback, troubleshooting

**Comment by gavind87** [comment] 2018-12-15 11:41
I'm having the same issue trying to flash with an Rpi
What could it be ? 
@woudenbe did you find out more information ? 
Quite lost and disappointed as I have 3 of these currently and none of them will flash

**Comment by woudenbe** [comment] 2018-12-15 12:36
I have flashed 5 sonof pow units now with a PL2303HX.  i still have one left that i cannot flash

**Comment by gavind87** [comment] 2018-12-15 16:35
@woudenbe so I managed to flash it on my Mac with a usb-ftdi 

Weird. Truly weird

**Comment by seritos** [comment] 2018-12-30 20:00
Hello everyone,

I am also having some issues trying to flash the new pow R2 v2.0. I have one FT232x that has given me no issues at all with other devices. 
After reading your coments... what is the correct procedure to do so? 
Thanx!

**Comment by Jason2866** [comment] 2018-12-30 20:09
Buy a usb serial adapter with a CH340 chip, with 3.3 volt support.
FTDI can work but is extremly out of it specs. It is not rated to deliver the needed current on the 3.3v rail

**Comment by Jason2866** [comment] 2018-12-30 20:36
It is the same procedure. Just pressing and holding button before you connect
power and tx rx gnd. After connecting you can release the button
Now start esptool to flash
Flashing process is described in wiki

**Comment by seritos** [comment] 2018-12-31 01:42
The adaptor cable wasnt good enough. Replaced and working perfectly

**Comment by michalstral** [comment] 2019-04-27 21:52
> Buy a usb serial adapter with a CH340 chip, with 3.3 volt support.
> FTDI can work but is extremly out of it specs. It is not rated to deliver the needed current on the 3.3v rail

I did what Jason2866 said and after issues with FTDI cheap adapter I used CH340G on Wifi Witty board and it works without problems. Thanks Jason2866, you saved me a hour at least.

**Comment by adverserath** [comment] 2021-03-29 00:05
FML that was hard to flash. Tried FTDI, Raspberry PI and CH340G. Had no success with any. Could get a minicom though, then checked the pins to the chip on my multimeter and there was a break in the board connection between the chip and the pin! Had to flash it holding my multimeter pin onto the chip with a crocodile clip on a wire to the CH340G. I hope to god I dont need to reflash that one.
Anyway, CH340G is the way to go!

**Comment by esbenr** [comment] 2021-04-17 18:46
I have the same problem Using an Arduino with Reset to GND to disable the Atmel chip.
Any generic solution other than buying specific hardware that "maybe" works?

**Comment by jziolkowski** [comment] 2021-04-17 21:37
Yes, heed to what wiki says and buy a USB adapter based on CH340G.

**Comment by Belsebub** [comment] 2021-08-03 15:16
Hi all

I have a strange problem with exactly this board when trying to flash using a raspi4.
At the moment I connect VDD with 3.3v PIN1 on raspi, the raspi reboots not matter if the button is pushed or not...
What did I wrong ?

**Comment by Jason2866** [comment] 2021-08-03 20:20
Powering from PI is problematic. Pi does not deliver enough current
