### ISSUE TITLE
BlitzWolf® BW-SHP6 EU

### ISSUE THREAD

**Issue by WladyX** [arendst/Sonoff-Tasmota#4091] opened 2018-10-17 05:47 UTC
Hi,
Will this socket be supported on tasmota?
https://www.banggood.com/BlitzWolf-BW-SHP6-EU-Plug-Metering-Version-WIFI-Smart-Socket-220V-240V-10A-Work-with-Amazon-Alexa-p-1356981.html

Thank you very much for your support.

**Comment by Frogmore42** [comment] 2018-10-17 06:08
Until someone buys one and opens one up to confirm if it has an esp8266 and exactly how it is wired, the answer is no.

**Comment by arendst** [comment] 2018-10-17 12:08
On order. Planned shipment mid November :-(

**Comment by WladyX** [comment] 2018-10-17 12:29
Nice, keep us updated, thank you!

**Comment by ghmax** [comment] 2018-10-17 20:44
Hello,
looks like a clone of the gosund sp-111. Own a couple of those devices and flashed wiith tasmota and espurna. Working perfectly.
https://www.amazon.de/Gosund-Stromverbrauch-Fernsteurung-Schaltbare-funktioniert/dp/B07FVR7PG7

regards,
max

**Comment by arendst** [comment] 2018-10-21 12:07
Hi @ghmax when using tasmota what module type did you select? And does energy monitoring work too?

Thx in advance.

**Comment by ionultd** [comment] 2018-10-21 21:19
I have the Blitzwolf BW-SHP2 smart plug open. I see the Wifi module with can so cannot see the chip. There is as usual connection to the RW/TX. How would one confirm if it is an ESP?

**Comment by ghmax** [comment] 2018-10-22 14:21
@ionultd ... just have a look at https://github.com/arendst/Sonoff-Tasmota/wiki - your device is already supported so that should be confirmation enough.

**Comment by hschroyen** [comment] 2018-10-26 07:34
Can this link help?

https://www.bastelbunker.de/gosund-sp111-mit-tasmota/

**Comment by Jason2866** [comment] 2018-10-27 12:34
Just needs to be confirmed to be 100% sure.
At the moment 99% that BW-SHP6 EU will work because it is the same hardware as Gosund SP111
which works with settings for BlitzWolf SHP2.
So if you have the chance to buy for a good price, do it!

**Comment by Jason2866** [comment] 2018-11-02 13:55
@jobhh  Feel free to do. Everyone can do

**Comment by jobhh** [comment] 2018-11-02 14:41
@Jason2866 Thank you for giving me permission 😄 Banggood hasn't shipped yet, so it will be some time before I can.

Joking aside. I was merely stating that, assuming the BW-SHP6 is not in the RELEASENOTES.md prematurely, this ticket seems to be resolved.

**Comment by mcer12** [comment] 2018-11-05 14:44
@ghmax How did you manage to open it without breaking the casing?

**Comment by ghmax** [comment] 2018-11-05 14:59
@mcer12 there is one screw on the side which you plug into an existing socket... The postet link (https://www.bastelbunker.de/gosund-sp111-mit-tasmota/) explains everything and shows pictures.

**Comment by mcer12** [comment] 2018-11-05 15:03
@ghmax Great! Many thanks!

**Comment by mcer12** [comment] 2018-11-05 15:17
I find it questionable how small gap is between high and low voltage sides of the board. I'm no expert but is that even safe?

**Comment by ascillato2** [comment] 2018-11-09 14:34
Hi,

Closing as @ghmax has confirmed that it is working.

> that was the Blitzwolf Module. Powermonitoring is also working.

**Closed by ascillato2** 2018-11-09 14:34 UTC
Labels: enhancement
