### ISSUE TITLE
sdm230 shutdown does not reset readings

### ISSUE THREAD

**Issue by servim** [arendst/Sonoff-Tasmota#5867] opened 2019-05-28 09:12 UTC
Hi!
When disconnecting sdm230 from electricity, the latest data from cdm230 continue to be published on the Tasmot web page, which is misleading. Is this a limitation of the protocol or can it be fixed so that when the sdm230 is disconnected, the readings are cleared?
Thanks :)

**Comment by Jason2866** [comment] 2019-05-28 10:28
It is by design, since SDM230 are build to be always connected to AC.

**Comment by ascillato2** [comment] 2019-05-28 11:33
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed by ascillato2** 2019-05-28 11:33 UTC

**Comment by Jason2866** [comment] 2019-05-28 11:42
@ascillato2 and @servim 
@curzon01 will do a PR to change behaviour. We have discussed and doing as suggested is possible and a better behaviour.
Thx for your suggestion!

**Comment by servim** [comment] 2019-05-28 12:50
pzem004t the same situation.
