### ISSUE TITLE
PowerOnState seems to work accidentially. Proposal to fix is

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#380] opened 2017-04-24 17:07 UTC
Hi all,

during my investigation to enable TASMOTA also for up to 32 relays, I found the PowerOnState functions and investigated them. The << and >> of the mask to get values only for the defined did not work with uint32_t. I did some debugging and found that (1<<Maxdevices)-1 did the job as well and reliable also with larger numbers. therefore see the proposed attached code changes. 

Also, the ESP.getResetReason should be configurable. Only if this value is there the toggle/on/off is working. e.g. the Wemos Mino never starts with this message. There it is "External system"

```
  if (sysCfg.module == MOTOR) sysCfg.poweronstate = 1;  // Needs always on else in limbo!
  if (ESP.getResetReason() == "Power On") {
  //if (sysCfg.poweronstate) {
    //snprintf_P(log, sizeof(log), PSTR("APP: maxdevices  %d"), Maxdevice);
    addLog(LOG_LEVEL_INFO, log);
    if (sysCfg.poweronstate == 0) {       // All off
      //snprintf_P(log, sizeof(log), PSTR("APP: Setting powermatrix all OFF 0x%8x"),power);
      power = 0;
      setRelay(power);
    }
    else if (sysCfg.poweronstate == 1) {  // All on
      power = (1<<Maxdevice)-1;
      //snprintf_P(log, sizeof(log), PSTR("APP: Setting powermatrix all ON 0x%8x"),power);
      setRelay(power);
    }
    else if (sysCfg.poweronstate == 2) {  // All saved state toggle
      power = (sysCfg.power & (1<<Maxdevice)-1 ) ^ 0xFFFFFFFF;
      if (sysCfg.savestate) setRelay(power);
      //snprintf_P(log, sizeof(log), PSTR("APP: Setting powermatrix all toggle 0x%8x"),power);
    }
    else if (sysCfg.poweronstate == 3) {  // All saved state
      power = sysCfg.power & (1<<Maxdevice)-1 ;
      if (sysCfg.savestate) setRelay(power);
      //snprintf_P(log, sizeof(log), PSTR("APP: Setting powermatrix all saved 0x%8x"),power);
    }
  } else {
    power = sysCfg.power & (1<<Maxdevice)-1 ;
    if (sysCfg.savestate) setRelay(power);
    //snprintf_P(log, sizeof(log), PSTR("APP: Setting powermatrix savestate 0x%8x, from 0x%8x, shifter is 0x%8x, maxdevice %d"),power, sysCfg.power, (1<<Maxdevice)-1 , Maxdevice);

  }
  addLog(LOG_LEVEL_INFO, log);
  blink_powersave = power;
```

**Comment by CommodoreWhite** [comment] 2017-04-24 19:45
Hi. I am encouraged by the results into investigating the power-on status returned by your Wemos Mino. You appear to be experiencing the same issue I have has with my v1.5 Electrodragons in that they also return "External System", see issue #284. I have not heard of other dragon owners experiencing this problem, perhaps this thread will help bottom out the issue.

Peter

**Comment by raisude** [comment] 2017-04-24 20:01
I have a sonoff sv. The relay works as a potential free contact. In my case it opens a sliding gate.I have also the problem that PowerOnState 0 does not do the right thing. After powering on the sonoff the power is On. So the gate opens.

Would be very nice if this problem could be fixed.

**Comment by arendst** [comment] 2017-04-28 12:45
@stefanbode thanks for your research. I will update mine with your suggestion regarding ``(1<<Maxdevice)-1``.

I'm still investigating the power on issue. I hoped to use a RAM value which would be different after power on than at restart but currently I fail to find a functional solution; I can't get a value on the heap which keeps it's state after restart...

**Comment by mrmin24** [comment] 2017-05-03 16:18
This does not seem to be fixed in latest release? or is it just me for wemos?

**Comment by stefanbode** [comment] 2017-05-03 16:29
I checked the code and it looked like it is fixed by access some global variables. Should work but haven't tried so far

**Comment by arendst** [comment] 2017-05-03 17:57
Remember that it should only trigger at power on OR external system. By design it should not trigger if you perform a restart.

**Comment by mrmin24** [comment] 2017-05-03 19:50
{"PowerOnState":1}

{"Started":"External System"}

still relays not on. keep old state 

Side note. This is with the PCF8574 8 relay configuration from @stefanbode and the normal wemos with 4 relays

**Comment by arendst** [comment] 2017-05-03 19:52
I do not support this feature. Over to @stefanbode ...

**Comment by mrmin24** [comment] 2017-05-03 19:59
sorry, to be clear. 

I tested **both** the options. Normal wemos and PCF8574. Same result

**Comment by arendst** [comment] 2017-05-03 20:01
How do you test my option? How do you disconnect and re-connect power to the wemos?

**Comment by mrmin24** [comment] 2017-05-03 20:12
I plug it out and back in again. USB and then get the {"Started":"External System"} reply

**Comment by arendst** [comment] 2017-05-03 20:13
Right. I'll test mine...

**Comment by arendst** [comment] 2017-05-03 20:21
I see a press on the reset button works fine and performs poweronstate correctly. Plugging USB out and then in again doesn't work although the restart message is the same. Somewhere in between power settling and poweronstate test something goes wrong on the Wemos only...

**Comment by mrmin24** [comment] 2017-05-03 20:27
my reset button also does not work

**Comment by arendst** [comment] 2017-05-04 08:43
The problem with the Wemos D1 mini is caused by the Serial RTS circuit which, when the host initialises the USB serial interface, lowers GPIO00 which in turn will toggle the relay. 

This is what happens after reinserting the USB cable in your COM port:
1) Wemos boots up, checks resetinforeason and performs task poweronstate
2) Host serial initialises and within a second the Wemos RTS line is pulled low resulting in GPIO00 pulled low which is recognised as a button press and toggles the relay.

The obvious solution is to power the (production) wemos D1 mini from an external power supply or use a USB cable without data lines as does the Sonoff SC.

**Comment by mrmin24** [comment] 2017-05-04 19:36
I powered the wemos from a Cellphone charger and used my SC cable. Still same result. 

00:00:07 MQTT: tele/42/INFO3 = {"Started":"External System"}
00:00:08 MQTT: ctrlIn/42/RESULT = {"POWER1":"OFF"}
00:00:08 MQTT: ctrlIn/42/POWER1 = OFF
00:00:08 MQTT: ctrlIn/42/RESULT = {"POWER2":"ON"}
00:00:08 MQTT: ctrlIn/42/POWER2 = ON
00:00:08 MQTT: ctrlIn/42/RESULT = {"POWER3":"ON"}
00:00:08 MQTT: ctrlIn/42/POWER3 = ON
00:00:08 MQTT: ctrlIn/42/RESULT = {"POWER4":"OFF"}
00:00:08 MQTT: ctrlIn/42/POWER4 = OFF

Then I tested baseline **(Program version	5.0.3)**   and it seems to be working correctly now on Wemos mini.

Thanks a lot

**Closed** 2017-05-10 10:58 UTC
Labels: enhancement
