### ISSUE TITLE
Generic Network problems using ESP-Arduino library 2.4.0

### ISSUE THREAD

**Issue by aferraz** [arendst/Sonoff-Tasmota#1900] opened 2018-02-13 19:38 UTC
Hi @arendst,
 after upgrading to the release v5.12.0a, 2 days ago,  I notice reachability problems on all my NodeMCU and Electrodragon board. In the log I notice continuous connection attempts to the mqtt broker and ping lost for all boards.
Following ad example:
Feb 13 18:28:34 esp14 esp14-1845 ESP-MQT: Attempting connection...
Feb 13 18:28:34 esp14 esp14-1845 ESP-MQT: Connected
Feb 13 18:28:34 esp14 esp14-1845 ESP-MQT: tele/esp14/LWT = Online (retained)
Feb 13 18:28:34 esp14 esp14-1845 ESP-MQT: cmnd/esp14/POWER = 
Feb 13 18:29:04 esp14 esp14-1845 ESP-MQT: Attempting connection...
Feb 13 18:29:04 esp14 esp14-1845 ESP-MQT: Connected
Feb 13 18:29:04 esp14 esp14-1845 ESP-MQT: tele/esp14/LWT = Online (retained)
Feb 13 18:29:04 esp14 esp14-1845 ESP-MQT: cmnd/esp14/POWER = 
Feb 13 18:29:44 esp14 esp14-1845 ESP-MQT: Attempting connection...
Feb 13 18:29:44 esp14 esp14-1845 ESP-MQT: Connected
Feb 13 18:29:44 esp14 esp14-1845 ESP-MQT: tele/esp14/LWT = Online (retained)
Feb 13 18:29:44 esp14 esp14-1845 ESP-MQT: cmnd/esp14/POWER = 
Feb 13 18:30:14 esp14 esp14-1845 ESP-MQT: Attempting connection...
Feb 13 18:30:14 esp14 esp14-1845 ESP-MQT: Connected
Feb 13 18:30:14 esp14 esp14-1845 ESP-MQT: tele/esp14/LWT = Online (retained)

Some minutes ago I'm back to version 5.9.1i and the connection attempts have disappeared.

I have also updated all my POWs to version v5.12.0a but no problems in this case.
What do you think can cause the problems?

Thank you 
 Alessandro

**Comment by arendst** [comment] 2018-02-14 09:40
I've seen this too but only on some devices and only with 2.4.0 library. Workaround is using the (2.3.0) pre-compiled release images or compile it yourself using the 2.3.0 library. I then was able to upload a 2.4.0 image which works well too.
 
I think the problem is with the SDK version used in 2.4.0 using part of flash to store wifi performance parameters which might get overwritten by my flash usage. I will investigate but it will take time as I have to create the issue and get flash dumps to pinpoint the issue.

The first step is to find out where the esp/arduino team has decided to store the SDK wifi performance parameters in flash as this is a user controlled area to made known to the SDK using a fixed callback routine.

**Comment by aferraz** [comment] 2018-02-14 10:43
@arendst your solution works perfectly.
I do not know if it is appropriate to keep this issue open.
Thanks you

**Comment by aferraz** [comment] 2018-02-14 11:03
@arendst I tried it seems to work. 
I leave this issue open for the benefit of others, if you think it's appropriate, you can close it.

Thank you

**Comment by aferraz** [comment] 2018-02-14 12:37
@arendst after about 1 hour of uptime, with version 2.4, the problem stared again.
I have recompiled with 2.3 and upgraded all boards. At the moment everything seems OK

**Comment by arendst** [comment] 2018-02-15 08:54
Investigation so far revealed that my initial thought is not the cause of the problem; flash is not compromised or corrupted leading to the TCP/IP problems. In fact the flash area used is FCxxx (or 4 blocks down from the end of flash) which I do not use.

I'm currently running a staged (2.4.0 + latest commits) version which seems to run fine but it is too early to make any conclusions yet. This version contains some changes regarding lwip2

**Comment by jjlawren** [comment] 2018-03-12 20:11
I've been having issues with frequent disconnections on a Basic using 5.12.0e with the 2.4.0 SDK. After seeing this case I've rolled the SDK back to 2.3.0 and I haven't had any disconnections in the first 2 hours of uptime.

@arendst, is there a straightforward way to test the latest 2.4.0 + commits version you referenced with PlatformIO?

**Comment by bigbuglamer** [comment] 2018-03-13 19:52
If i understand correctly then it's fixed in 2.4.1

https://github.com/esp8266/Arduino/pull/4105

**Comment by aferraz** [comment] 2018-03-19 19:29
@arendst any news about this ?
Thanks
 Alessandro

**Comment by arendst** [comment] 2018-03-19 22:04
Your guess is as good as mine. I suggest you keep an eye on the esp arduino issue list. I'll wait for 2.4.2 as then some problems will be solved and others maybe introduced sadly.

**Comment by aferraz** [comment] 2018-03-23 14:33
Thanks @arendst . I will

**Comment by ascillato2** [comment] 2018-08-18 06:12
New 2.4.2 esp8266 library has been released. Please, use 2.3.0 or the latest. Avoid 2.4.0

**Closed by ascillato2** 2018-08-18 06:12 UTC
Labels: bug
