### ISSUE TITLE
Pulsetime remaining time issues

### ISSUE THREAD

**Issue by royby12** [arendst/Sonoff-Tasmota#4453] opened 2018-11-25 23:18 UTC
Hi Guys,
I found couple of issues while working with the Pulsetime:
1. when setting pulsetime when power is off - Active countdown starts although power is off:
00:12:02 CMD: power
00:12:02 RSL: RESULT = {"POWER":"OFF"}
00:12:02 RSL: POWER = OFF
00:12:06 CMD: PulseTime 300
00:12:06 RSL: RESULT = {"PulseTime1":"300 (Active 300)"}
00:12:10 CMD: PulseTime
00:12:10 RSL: RESULT = {"PulseTime1":"300 (Active 296)"}

2. When pulsetime is set and device is On - Sending "Power" to get status is reseting the Active counter:

00:15:24 CMD: PulseTime
00:15:24 RSL: RESULT = {"PulseTime1":"300 (Active 0)"}
00:15:35 CMD: power on
00:15:35 RSL: RESULT = {"POWER":"ON"}
00:15:35 RSL: POWER = ON
00:15:38 CMD: PulseTime
00:15:38 RSL: RESULT = {"PulseTime1":"300 (Active 296)"}
00:15:44 CMD: PulseTime
00:15:44 RSL: RESULT = {"PulseTime1":"300 (Active 290)"}
00:15:47 CMD: power
00:15:47 RSL: RESULT = {"POWER":"ON"}
00:15:47 RSL: POWER = ON
00:15:50 CMD: PulseTime
00:15:50 RSL: RESULT = {"PulseTime1":"300 (Active 0)"}

Hope you guys can fix it.

Thanks,
Roy

**Comment by ascillato** [comment] 2018-11-26 00:05
Hi,

That is by design. Please read the wiki at commands. Thanks

**Comment by ascillato2** [comment] 2018-11-26 00:14
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Closed by ascillato2** 2018-11-26 00:14 UTC
Labels: question
