### ISSUE TITLE
RGBW light bulb feature request

### ISSUE THREAD

**Issue by AalianKhan** [arendst/Sonoff-Tasmota#6075] opened 2019-07-12 01:10 UTC
**Have you look for this feature in other issues and in the wiki?**
yes
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._
I have tuya converted Tasnota in a Teckin SB50 RGBW bulb. It works great and I really like it but the RGB LEDs are weaker and the White LEDs are brighter and stronger. I would like Tasmota to be able to detect when the RGB equal to 255,255,255 then turn on the White LEDs instead of making a weak RGB mix to make white.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
A command or a set option to be able to switch to white LEDs when RGB = 255,255,255
**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
I have used Home assistant automation to switch over to White LEDs but there is a noticeable wait and I would like it to be internal in case my internet goes down.
**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by s-hadinger** [comment] 2019-07-12 06:02
Duplicate of #5704 

Good news: it's already in the code.
Bad news: it's not yet in the wiki, I'm late on this one. Please see PR #6032 

Short version: use `rgbwwtable 255,255,255,255,0` or adjust white power with `rgbwwtable 255,255,255,<w>,0` where <w> is max power you want to send to the white channel.

**Closed** 2019-07-12 12:00 UTC
Labels: duplicated
