### ISSUE TITLE
Two way switch with sync status

### ISSUE THREAD

**Issue by AdvaitT17** [arendst/Sonoff-Tasmota#6554] opened 2019-10-03 06:42 UTC
I have a sonoff 4 ch pro and 4 two-way switches...I want to connect them such that when I use the regular two-way switch it will get sync within the app as well. Is this possible? Please help...

**Comment by andrethomas2** [comment] 2019-10-03 07:13
Duplicate of #6553

**Closed by andrethomas2** 2019-10-03 07:13 UTC
