### ISSUE TITLE
MCP23017 not updating status

### ISSUE THREAD

**Issue by MadDoct** [arendst/Sonoff-Tasmota#3350] opened 2018-07-27 22:38 UTC
Make sure these boxes are checked [x] before submitting your issue - Thank you!

[x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
[x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
[x ] Searched the problem in the forum (https://forum.digital-pig.com/)
[x ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
 Hardware used : Nodemcu v3 (lolin), mcp23017 with breakout board.

in 6.1.1c, using the mcp23017, the status of the pins isn't published when they change although I set the pins using sensor29 7,2,1, for example... If I use status 10, the value of the pins is correct, but the behavior is the same no matter if I use pinmode 1, 2, 3 or 4.
The wiring was correct because I tried espeasy and the mcp works perfectly...
(I will provide more info when I get home)

Status result:
15:49:02 MQT: stat/NodeMCUt/STATUS = {"Status":{"Module":18,"FriendlyName":["NodeMCUtasmota"],"Topic":"NodeMCUt","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
Status 10 result:
15:48:01 MQT: stat/NodeMCUt/STATUS10 = {"StatusSNS":{"Time":"2018-07-28T15:48:01","ANALOG":{"A0":0},"MCP230XX":{"D0":1,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":0,"D8":0,"D9":0,"D10":0,"D11":0,"D12":0,"D13":0,"D14":0,"D15":0}}}

**Comment by Frogmore42** [comment] 2018-07-28 00:37
Huh?
You'll need to provide the information listed in the template, in particular, a clear description of the problem.
I certainly don't understand what is written.

The only thing I can think of, is you changed the module type and the pins definitions at the same time.  When you change the module type in the web UI, it resets the pin definitions to the default for the module.  You can/have to then change the definition for the pins.

**Comment by MadDoct** [comment] 2018-07-28 15:37
"Solved" it by enabling the pull-up resistors for all pins! Maybe that should be written in the wiki and/or set by default...

**Comment by andrethomas** [comment] 2018-07-28 15:41
`"Solved" it by enabling the pull-up resistors for all pins! Maybe that should be written in the wiki and/or set by default...`

I do not think one wants to enable pull-up by default - by default, this would be done externally by whatever is connected to the pin so the option to enable it is only for specific uses like connecting a button directly to a pin and would not be the default use for any particular user. Hence it defaults to disabled but can easily be enabled as you have done :)

**Comment by MadDoct** [comment] 2018-07-28 15:46
From what I could test, no enabling the pull-up meant that the values were constantly floating!
What other uses could you have for the mcp, the way it is implemented - as a senao -, other than switches or binary sensors?

**Comment by andrethomas** [comment] 2018-07-28 15:50
For example, I have them connected to PIR sensors that pull the pin high by default - if the PIR is triggered it pulls the pin LOW... if the wire is cut or the power removed from the PIR the pin goes LOW which would not happen if internal pull-up was enabled and lead to not detecting a PIR which wires have been snipped...

The default of the chip on power-up is input without pull-up according to the datasheet so this also needs to be taken into consideration insofar that normal usage of the chip would require you to specifically enable pull up resistors.

**Comment by andrethomas** [comment] 2018-07-28 15:58
I guess adding the pullup for `sensor29 reset` by default wouldn't hurt either

**Comment by MadDoct** [comment] 2018-07-28 15:58
Ok, that way I understand, but it should be noted in the wiki that some kind of pull-up or pull-down should be used, internal or external, because the values keep floating... Also, I had to enable the pull-up on all to start getting the intents... Enabling on that specific pin had no result!

**Comment by MadDoct** [comment] 2018-07-28 16:00
Or adding an option to enable all easily...

**Comment by andrethomas** [comment] 2018-07-28 16:56
You mean something like

```
sensor29 reset   // Reset all pins to input with pull-up disabled (datasheet default)
sensor29 reset1  // Reset all pins to input without interrupt and with pull-up enabled
sensor29 reset2  // Reset all pins to input with interrupt on change change and with pull-up enabled
sensor29 reset3  // Reset all pins to input with interrupt on LOW and with pull-up enabled
sensor29 reset4  // Reset all pins to input with interrupt on HIGH and with pull-up enabled

```

That will cost another 80 bytes of flash.

**Comment by MadDoct** [comment] 2018-07-28 18:00
That would be a great idea, but above all, there should be a heads up in the wiki and maybe an investigation to understand why the intent is only sent when all, or at least, several pins have the pull up activated...

**Comment by andrethomas** [comment] 2018-07-28 18:03
The interrupts are not intended to update the Sensor 10 command's output - The interrupts provide MQTT outputs for each instance on any given pin... So I guess I still don't understand what you mean.

**Comment by MadDoct** [comment] 2018-07-28 18:11
I know that. I only talked about status 10 to show you that the mcp was connected andthe pins were changing as they should... The problem is that, unless the pull-ups are activated on ALL the pins (or at least several), the intents aren't generating the MQTT outputs they should...

**Comment by andrethomas** [comment] 2018-07-28 18:16
I'm unable to reproduce your experience - interrupts work for me whether pull-ups are enabled or not...

**Comment by MadDoct** [comment] 2018-07-28 18:21
That's strange... Maybe a problem on my mcp... I'm using one with a breakout board... Did you wire something besides de GND, VCC, SDA and SCL? (besides the GPIOs, obviously..)

**Comment by MadDoct** [comment] 2018-07-28 18:29
Mine doesn't generate the interrupt if only one or two are used...

**Comment by andrethomas** [comment] 2018-07-28 18:36
To recreate

```
20:30:38 CMD: sensor29 reset
20:30:38 SRC: Serial
20:30:38 RSL: Group 0, Index 29, Command SENSOR, Data reset
20:30:38 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":99,"MODE":1,"PULL-UP":0}}

```
This sets all pins to input without pull-up but pinmode = 1 so there's no interrupt.

I then set pin 0 to pinmode 2 (interrupt on change) without pull-up
```
20:31:18 CMD: sensor29 0,2,0
20:31:18 SRC: Serial
20:31:18 RSL: Group 0, Index 29, Command SENSOR, Data 0,2,0
20:31:18 MQT: stat/sonoff/RESULT = {"Sensor29":{"D":0,"MODE":2,"PULL-UP":0}}

```

I get nothing until I put a dupont wire into the pin on the breadboard which obviusly causes it to oscillate based on interference picked up from my finger and the absense of a pull-up or pull-down setup and produces something like this:

![image](https://user-images.githubusercontent.com/470015/43359612-4fc96424-92a5-11e8-98c4-fe6c1969c93b.png)

So this is generating interrupts on A0 on the MCP23017 and pushing it out on MQTT whilst all the other pins are still pinmode = 1 (no interrupt) and no pull-ups enabled

If I enable pull-up or externally pull up or pull down the pin then it only occurs as and when I connect to the relevant voltage line.

**Comment by andrethomas** [comment] 2018-07-28 19:01
I've added a section in the wiki to cover use of interrupts on pins which are stateless/floating.

**Comment by MadDoct** [comment] 2018-07-28 22:36
Strangely, for me, I get floating values even without Dupont wires attached... (Maybe a problem with my mcp - are you using one with a break out board or stand alone?) 
But that would only increase the number of intents... My problem is the opposite, the values change but the intents aren't producing a result... The intents only work after setting the pull-ups for all or, at least, several pins...
I'm using 6.1.1c, with core 2.3. What version are you using? Could that be the problem?

**Comment by andrethomas** [comment] 2018-07-29 11:31
> Strangely, for me, I get floating values even without Dupont wires attached... (Maybe a problem with my mcp - are you using one with a break out board or stand alone?)

Standalone ESP8266 with a MCP on breadboard. I have two, one wired for MCP23008 and one wired for MCP23017

![image](https://user-images.githubusercontent.com/470015/43365848-79fd9f10-9333-11e8-9f1f-72e9b4957b24.png)

![image](https://user-images.githubusercontent.com/470015/43365852-932501cc-9333-11e8-9581-66f253b7e4ec.png)

> Did you wire something besides de GND, VCC, SDA and SCL? (besides the GPIOs, obviously..)

Yes, the reset pin on the MCP is tied to VCC (3.3V)

> But that would only increase the number of intents... My problem is the opposite, the values change but the intents aren't producing a result (maybe too many changes simultaneously?!)... The intents only work after setting the pull-ups for all or, at least, several pins...
> I'm using 6.1.1c, with core 2.3. What version are you using? Could that be the problem?
> 

I use 2.4.1 but I have tested it with 2.3.0 and 2.4.0 with the same result as expected.

**Comment by andrethomas** [comment] 2018-07-29 11:45
> (maybe too many changes simultaneously?!)

Too many would not make it not cause an interrupt - perhaps missing interrupts in between is possible as the register is only read every 50 milliseconds - The register can only report on the last interrupt which occurred, but if at least one was set in the 50 milliseconds since the last check it will still report it via MQTT - Also remember that the interrupts are not reported to telemetry data sent via MQTT based on logging interval configured for your module and will also only the current state of a particular pin (not the interrupt) on telemetry data and/or status 10. Interrupts are ONLY reported via MQTT output as follows:

`13:23:44 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T13:23:44","MCP230XX_INT":{"Pin":"D0", "State":1}}`

**Comment by andrethomas** [comment] 2018-07-29 12:20
For a more scientific approach I did this as a test

`sensor29 0,2,0`

Then create an arduino UNO (5V) with the following sketch and connected D2 output pin to pin 0 on mcp23017

```
void setup() {
  pinMode(2,OUTPUT);
}

void loop() {
  digitalWrite(2,LOW);
  delay(1000);
  digitalWrite(2,HIGH);
  delay(1000);
}
```

I get the expected output on the Tasmota firmware:

```
14:14:00 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:14:00","MCP230XX_INT":{"Pin":"D0", "State":0}}
14:14:01 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:14:01","MCP230XX_INT":{"Pin":"D0", "State":1}}
14:14:02 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:14:02","MCP230XX_INT":{"Pin":"D0", "State":0}}
14:14:03 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:14:03","MCP230XX_INT":{"Pin":"D0", "State":1}}
14:14:04 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:14:04","MCP230XX_INT":{"Pin":"D0", "State":0}}
14:14:05 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:14:05","MCP230XX_INT":{"Pin":"D0", "State":1}}

```

Lets try interrupt on LOW
`sensor29 0,3,0`

```
14:16:14 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:16:14","MCP230XX_INT":{"Pin":"D0", "State":0}}
14:16:16 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:16:16","MCP230XX_INT":{"Pin":"D0", "State":0}}
14:16:18 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:16:18","MCP230XX_INT":{"Pin":"D0", "State":0}}
14:16:20 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:16:20","MCP230XX_INT":{"Pin":"D0", "State":0}}
14:16:22 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:16:22","MCP230XX_INT":{"Pin":"D0", "State":0}}

```

Goes LOW every 2 seconds as expected and interrupt is reported via MQTT

Lets try interrupt on HIGH
`sensor29 0,4,0`

```
14:17:33 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:17:33","MCP230XX_INT":{"Pin":"D0", "State":1}}
14:17:35 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:17:35","MCP230XX_INT":{"Pin":"D0", "State":1}}
14:17:37 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:17:37","MCP230XX_INT":{"Pin":"D0", "State":1}}
14:17:39 MQT: stat/sonoff/RESULT = {"Time":"2018-07-29T14:17:39","MCP230XX_INT":{"Pin":"D0", "State":1}}
```

Again, as expected, interrupt provided via MQTT on HIGH

In all these cases the pull-up was disabled as the Arduino UNO dictated the state of the pin.

**Comment by andrethomas** [comment] 2018-07-29 12:43
Hmm, hang on, I think I found something weird - will report back

**Comment by andrethomas** [comment] 2018-07-29 13:31
@MadDoct Please change line 149 in xsns_29_mcp230xx.ino from
switch (Settings.mcp230xx_config[+(mcp230xx_port*8)].pinmode) {
to
switch (Settings.mcp230xx_config[intp+(mcp230xx_port*8)].pinmode) {

It was missing the intp picked up from the for loop which would have caused the code to incorrectly reference the pin configuration. This would cause int to only work if it was set in the corresponding bit for portB on the MCP.

I've made a PR for it here https://github.com/arendst/Sonoff-Tasmota/pull/3369 but you may apply the change directly until the PR is committed to development.

Please test again after and revert back - Thanks for the testing so far... without it I would not have detected the error as my "working as a device" where the PIR's are connected have all pins to pinmode 2.

**Comment by andrethomas** [comment] 2018-07-29 13:47
PR committed to development.

**Comment by MadDoct** [comment] 2018-07-29 16:14
I'm happy to confirm that it is now working flawlessly!
Glad I could help and thanx for the fix! ;)

**Comment by MadDoct** [comment] 2018-07-29 16:29
I made the change in my compilation and will try...

**Comment by MadDoct** [comment] 2018-07-29 16:41
tested and working... now to try rules...

**Comment by andrethomas** [comment] 2018-07-29 16:41
Change 164 to

`snprintf_P(mqtt_data, sizeof(mqtt_data), PSTR("%s,\"MCP230XX_INT\":{\"D%i\":%i}"), mqtt_data, intp+(mcp230xx_port*8), ((mcp230xx_intcap >> intp) & 0x01));`

Should work - have an example rule?

**Comment by MadDoct** [comment] 2018-07-29 17:06
I changed it by myself before and it works as expected, but the truth is that it isn't necessary when using rules because rules don't care about the MCP2300XX_INT, they just care if D0 is 1 or 0 (MCP2300XX) (when I asked you to change it I wasn't thinking clearly!)
By the way, I was able to use in rules to activate a relay successfully using:
rule on mcp230xx#d0=0 do power1 on endon on mcp230xx#d0=1 do power1 off endon
rule 5
It works like a charm! ;)
Now we really have additional inputs!!!! ;)

**Comment by andrethomas** [comment] 2018-07-29 17:16
Cool, well done and thanks again for testing.

**Comment by MadDoct** [comment] 2018-07-29 17:48
Can that driver be used to have some pins as input and some as output?

**Comment by andrethomas** [comment] 2018-07-29 17:50
Yup - it just adds pinmode 5 (for output) and sensor29 commands 
`sensor29 pin,ON`
`sensor29 pin,OFF`

The rest is the same as the one existing in the development branch here.

You can conditionally include or exclude it using the #define USE_MCP230xx_OUTPUT compiler directive in the config file

**Closed** 2018-07-29 18:13 UTC

**Comment by MadDoct** [comment] 2018-07-29 19:31
Just tested it and it works like a charm! Thanx!

**Comment by andrethomas** [comment] 2018-07-29 19:36
Good stuff!

Also, earlier change proposed has been commited to development and mcp230xx_output
```
snprintf_P(mqtt_data, sizeof(mqtt_data), PSTR("%s,\"MCP230XX_INT\":{\"D%i\":%i}"), mqtt_data, intp+(mcp230xx_port*8), ((mcp230xx_intcap >> intp) & 0x01));
```

**Comment by andrethomas** [comment] 2018-07-29 21:17
The rules only respond to the pin state reported by telemetry (same as status 10) - I need to find a way to publish the interrupt in such a way that it can be picked up by rules then it will work, I think.

**Comment by MadDoct** [comment] 2018-07-29 21:20
No, the rules work perfectly as is! The rule I put above worked very well... So, as trigger, it is perfect. The problem is using the outputs in an action using rules...

**Comment by MadDoct** [comment] 2018-07-29 21:30
The rule would probably be best used inverted, I mean on when 0 and off when 1... ;)

**Comment by andrethomas** [comment] 2018-07-29 21:31
Yeah, damn chinese with their inverted relays :)

**Comment by MadDoct** [comment] 2018-07-29 21:32
Could you add a third option? Besides on and off, there could also be a toggle... That would be perfect!

**Comment by andrethomas** [comment] 2018-07-29 21:33
Good idea, will work on it during the week... off to bed now 11:32pm :|

**Comment by MadDoct** [comment] 2018-07-29 21:34
I didn't mean the relays... If you activate the pull-ups, 1 will be the base and 0 will be the "activated" for the switch...

**Comment by andrethomas** [comment] 2018-07-29 21:34
Gotcha

**Comment by MadDoct** [comment] 2018-07-31 09:00
I've been doing some tests and have several sugestions for the output mode:
1 - When you disconnect the nodemcu from power and reconnect (not a software restart), the output pins always start LOW and keep LOW independently of how they were before... That's pretty bad if you're using active low relays...
2 - The telemetry should be changed to indicate that the pin is being used as output. The way it is, it makes the telemetry about that pin totally irrelevant and maybe misleading... Currently there's no info about that, unless you query the specific pin.
3 - Currently there's no way to know if the pin is on or off. The command sensor29 1,?, should return, if the pin is an output, the mode and on or off...

**Comment by andrethomas** [comment] 2018-07-31 09:10
Sure, all in good time - remember output mode is not officially supported by Tasmota.

I've added sensor29 pin,T for toggle to the mcp230xx_output fork but  have not yet tested it as I do not have hardware with me where I am right now.

The other stuff you mention is on the todo list... just not a priority as only the input is formally part of the Tasmota development codebase... output is still experimental and there are other things I am also adding which won't even require you to use rules to execute commands... but all in good time.

**Comment by andrethomas** [comment] 2018-07-31 16:52
@MadDoct Response has been update to include pin state with PR https://github.com/arendst/Sonoff-Tasmota/pull/3384

Change already comitted to mcp230xx_output

**Comment by andrethomas** [comment] 2018-07-31 18:39
@MadDoct 

To address your issue on output pins being low on startup for the mcp230xx_output fork I dual purposed the pullup option to set the default reset/power-up state of a pin.

This means
```
sensor29 0,5,0  // Pin will be low on reset/power-up
sensor29 0,5,1  // Pin will be high on reset/power-up
```

Trust that solves your inverted relay problem... so you can do `sensor29 pin,5,1` to specify that the pin will go high on reset/power-up

Note this is only applicable to the mcp230xx_output branch from here https://github.com/andrethomas/Sonoff-Tasmota/tree/mcp230xx_output

**Comment by andrethomas** [comment] 2018-08-01 16:06
@MadDoct Added PR https://github.com/arendst/Sonoff-Tasmota/pull/3391 which allows you to write rules that will respond immediately to interrupts and not based on the output provided by telemetry JSON data.

**Comment by andrethomas** [comment] 2018-08-01 16:25
@MadDoct Nah, it was getting it from the telemetry json...

See comments from Theo on the previous commit https://github.com/arendst/Sonoff-Tasmota/pull/3370

**Comment by andrethomas** [comment] 2018-08-01 16:26
> What I think is necessary, if you can, is to add a way for the output to be the same it was before powering off..

I will add code to the output branch/fork to adhere to the setoption0 setting, also defined in your config file as 
`#define SAVE_STATE             1`

**Comment by MadDoct** [comment] 2018-08-01 16:29
Believe me, it was working immediately! I've tested it allot!
Thanx for the latest commit! And for all of them!!!

**Comment by andrethomas** [comment] 2018-08-01 16:32
Cool, anyway the SAVE_STATE setting is used globally by the Tasmota firmware to save the state of relays configured the traditional way without using the MCP so its only logical that the output fork should adhere to this... it will save the state of the pin each time it changes, when it powers up it will first consult the default setting substituted by the pullup parameter and then look at the savestate if it is enabled and apply accordingly.

So saved state will always override default setting but if saved state is not enabled in the firmware (it is by default anyway) it will use the default set by the pullup parameter.

Will report back once I've implemented it on the output branch

**Comment by andrethomas** [comment] 2018-08-01 17:13
@MadDoct https://github.com/andrethomas/Sonoff-Tasmota/tree/mcp230xx_output now adheres to save_state / setoption0

**Comment by MadDoct** [comment] 2018-08-03 16:43
I've been testing and now, for example, 7,2,1 isn't activating the pull-up althout it replies as pull-up:1, the pin fluctuates...

**Comment by MadDoct** [comment] 2018-08-03 17:27
I'm probably wrong, but why would you put this? Is this the problem?
#if**n**def USE_MCP230xx_OUTPUT
      if (Settings.mcp230xx_config[idx+(mcp230xx_port*8)].pullup) {
        reg_gppu |= (1 << idx);
      }
#endif

Although USE_MCP230xx_OUTPUT is defined, it doesn't mean that we don't want to use input...
(My knowledge of c++ is VERY limited...)

**Comment by andrethomas** [comment] 2018-08-03 17:36
Apparently, your C isn't as limited as you think :)

Will make a PR to fix shortly.

**Comment by andrethomas** [comment] 2018-08-03 17:54
The defined caused the pre-processor to completely disable pull-up on all commands whereas it should be selective on whether or not a specific pin is in output mode (pinmode 5)

So we want pull-ups to work but not for pinmode 5

Grab a fresh copy of https://github.com/andrethomas/Sonoff-Tasmota/blob/mcp230xx_output/sonoff/xsns_29_mcp230xx.ino

Should be fixed now.

Nice find, Thanks!

**Comment by MadDoct** [comment] 2018-08-03 22:11
It would probably be a good idea to set pinmode 0 when you reset...

**Comment by andrethomas** [comment] 2018-08-03 22:25
> It would probably be a good idea to set pin mode 0 when you reset...

Reset adheres to datasheet's default power-up which is all pins floating input without the pull-up.

**Comment by MadDoct** [comment] 2018-08-03 22:27
Also, I added to my code two more reset modes, to start them all with pull-up enabled and another one to set pinmode 0 for all...
I've noticed that, in practive, pinmode 1 and 0 are the same, because it keeps returning the state of the pin even when set to 0, when you use Status 10

**Comment by andrethomas** [comment] 2018-08-03 22:29
Correct - 0 was originally used to "disable" a pin but has since been deprecated since not needing to use a pin having it in pin mode 1 is all the same anyway.

**Comment by MadDoct** [comment] 2018-08-03 22:39
So, there's no way to stop the mcp from reporting the status of the pin, to "save" processing from the esp? Because if the pins are constantly fluctuating, that could have an impact... From what I could tell from my testing, although tasmota isn't reporting the change by an int, it is in fact "aware" of the actual pin status...

**Comment by andrethomas** [comment] 2018-08-03 22:44
In pin mode 1 interrupts are not enabled so it has no additional impact.

**Comment by andrethomas** [comment] 2018-08-03 22:46
To be more clear the pins are not read individually... they are read as 8 bit registers... you cannot read only 1 bit without reading the entire register. I do not want to exclude the pin on telemetry data because it may have impact on how HA software handles the tele data.

**Comment by andrethomas** [comment] 2018-08-03 23:57
You should consider forking the codebase - might make it easier to handle any additional features you think may be useful - I think I've done what I wanted up to now except for the last item on my list

sensor29 status

While should provide a blob of the configuration data of the MCP230xx but that'll be staged for the development branch and then merged to the output branch after.

**Comment by MadDoct** [comment] 2018-08-04 10:11
Ok! I can see that you added new reset modes! ;)
Just a final remark... You should change the initial description from input only to input and output... ;)
Thanks for all the trouble you had!

**Comment by MadDoct** [comment] 2018-08-04 10:40
Also isn't this redundant?:
#ifdef USE_MCP230xx_OUTPUT
      if (Settings.mcp230xx_config[idx+(mcp230xx_port*8)].pullup && (Settings.mcp230xx_config[idx+(mcp230xx_port*8)].pinmode != 5)) {
        reg_gppu |= (1 << idx);
      }
#else
      if (Settings.mcp230xx_config[idx+(mcp230xx_port*8)].pullup) {
        reg_gppu |= (1 << idx);
      }
#endif
Can't it be just (if you don't define the use output, the pinmode will never be 5 anyway):
if (Settings.mcp230xx_config[idx+(mcp230xx_port*8)].pullup && (Settings.mcp230xx_config[idx+(mcp230xx_port*8)].pinmode != 5)) {
        reg_gppu |= (1 << idx);
}

**Comment by andrethomas** [comment] 2018-08-04 10:57
Well, it depends how you look at it.

It saves 16 bytes of flash and several cpu cycles (for the extra math involved) to optomise by using the relevant code block using compiler directives in the way which I did... the same form of redundancy you're suggesting may actually be relevant in other sections of the code and it all adds up :)

**Comment by andrethomas** [comment] 2018-08-04 12:07
Yup, that way user can decide if they want to use the extra flash required for OUTPUT or not... most people try keep their compiled binary below 502k to prevent not being able to flash OTA without having to revert to minimal first.

**Comment by andrethomas** [comment] 2018-08-04 13:13
In the same way, adding some features like the plan I had for sensor29 status to output like below already adds 712 bytes of flash which isnt really justified given the benefit it gives over sensor29 pin,?
```

14:04:43 CMD: sensor29 status
14:04:43 SRC: Serial
14:04:43 RSL: Group 0, Index 29, Command SENSOR, Data status
14:04:43 MCP23017: found at I2C address 0x20
14:04:43 MCP23017: PIN:0  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:1  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:2  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:3  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:4  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:5  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:6  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:7  MODE:INPUT NO INTERRUPT  PULL-UP:DISABLED
14:04:43 MCP23017: PIN:8  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:9  MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:10 MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:11 MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:12 MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:13 MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:14 MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MCP23017: PIN:15 MODE:INPUT INT ON CHANGE PULL-UP:ENABLED 
14:04:43 MQT: stat/sonoff/RESULT = {"SENSOR29 STATUS":"COMPLETE"}
```

So in this way some features are not plausable or do not trade off well for flash used if alternative method of obtaining the same is possible.

To put it into perspective, it increases the USE_MCP230xx codebase by 32% :|

**Comment by andrethomas** [comment] 2018-08-04 13:17
```
void MCP230xx_ShowStatus(void) {
  if (mcp230xx_type) {
    String chip_type = "MCP23008";
    if (mcp230xx_type == 2) chip_type = "MCP23017";
    snprintf_P(log_data,sizeof(log_data),"%s: found at I2C address 0x%x",chip_type.c_str(),mcp230xx_address);
    AddLog(LOG_LEVEL_DEBUG);
    for (uint8_t pinx = 0;pinx<mcp230xx_pincount;pinx++) {
      String pin = String(pinx);
      if (pinx < 10) pin=pin+" ";
      String pinmode = "NOT SET OR UNKNOWN ";
      String special_register = "PULL-UP";
      switch(Settings.mcp230xx_config[pinx].pinmode) {
        case 1:
          pinmode = "INPUT NO INTERRUPT ";
          break;
        case 2:
          pinmode = "INPUT INT ON CHANGE";
          break;
        case 3:
          pinmode = "INPUT INT ON LOW   ";
          break;
        case 4:
          pinmode = "INPUT INT ON HIGH  ";
          break;
        default:
          break;
      }
      String special_register_value = "DISABLED";
      if (Settings.mcp230xx_config[pinx].pullup) {
        special_register_value = "ENABLED ";
      }
      snprintf_P(log_data,sizeof(log_data),"%s: PIN:%s MODE:%s %s:%s",chip_type.c_str(),pin.c_str(),pinmode.c_str(),special_register.c_str(),special_register_value.c_str());
      AddLog(LOG_LEVEL_DEBUG);
    }
  } else {
    snprintf_P(log_data,sizeof(log_data),PSTR("MCP230XX: NOT FOUND"));
    AddLog(LOG_LEVEL_DEBUG);
  }
  snprintf_P(mqtt_data, sizeof(mqtt_data), PSTR("{\"SENSOR29 STATUS\":\"COMPLETE\"}"));
}
```

And add line to bool MCP230xx_Command(void)
`if (data == "STATUS") { MCP230xx_ShowStatus(); return serviced; }`

**Comment by MadDoct** [comment] 2018-08-04 14:17
Is it possible, when set as an output, for the status to appear on the webfront, as it happens with the "stock" relays?

**Comment by andrethomas** [comment] 2018-08-04 14:43
Status would be possible - toggle buttons not possible in an efficient way.

**Comment by MadDoct** [comment] 2018-08-04 14:45
Ok, that would be great!
I updated my comment... Did you see the new issue I found?

**Comment by andrethomas** [comment] 2018-08-04 14:47
Yeah, will check into it in a bit.

**Comment by andrethomas** [comment] 2018-08-04 15:45
Pin state after ON, OFF or T is now reported in R field
```
17:41:54 CMD: sensor29 0,ON
17:41:54 MQT: stat/sonoff/RESULT = {"S29cmnd":{"D":0,"C":"ON","R":1}}
17:41:58 CMD: sensor29 0,OFF
17:41:58 MQT: stat/sonoff/RESULT = {"S29cmnd":{"D":0,"C":"OFF","R":0}}
17:42:01 CMD: sensor29 0,T
17:42:01 MQT: stat/sonoff/RESULT = {"S29cmnd":{"D":0,"C":"TOGGLE","R":1}}
17:42:04 CMD: sensor29 0,T
17:42:04 MQT: stat/sonoff/RESULT = {"S29cmnd":{"D":0,"C":"TOGGLE","R":0}}
```

**Comment by MadDoct** [comment] 2018-08-04 15:48
Perfect!
Will keep testing...

**Comment by andrethomas** [comment] 2018-08-04 16:07
Added web display, but you need #ifdef USE_MCP230xx_DISPLAYOUTPUT in user_config.h - Adds 204 bytes of flash.

**Comment by andrethomas** [comment] 2018-08-04 16:16
```
USE_MCP230xx               +2264 bytes
USE_MCP230xx_OUTPUT         +608 bytes
USE_MCP230xx_DISPLAYOUTPUT  +204 bytes
```

Not half bad, I think.

**Comment by andrethomas** [comment] 2018-08-04 16:26
It only displays for output pins, but you can easily change it for all pins by taking out the conditional statement 

 ```
if (Settings.mcp230xx_config[pin].pinmode == 5) {
      snprintf_P(mqtt_data, sizeof(mqtt_data), HTTP_SNS_MCP230xx_OUTPUT, mqtt_data, pin, (gpio>>pin)&1);
}
```

and just leaving the snprintf_P in there

**Comment by MadDoct** [comment] 2018-08-05 10:50
Made my first pull-request.. see if you agree...

**Comment by MadDoct** [comment] 2018-08-05 14:50
Ok, but would only change one of the responses and not both

**Comment by MadDoct** [comment] 2018-08-05 22:42
Couldn't the result be published in a different topic altogether for each output pin, a little like the POWER1 of the relays? That would be even better...

**Comment by jsponz** [comment] 2018-08-07 13:43
@MadDoct how is your final configuration? Do you have inputs and outputs? I am fighting the same issues. Thanks!

**Comment by MadDoct** [comment] 2018-08-07 14:19
Yes, I have it working pretty well...

A terça, 7/08/2018, 14:44, jsponz <notifications@github.com> escreveu:

**Comment by MadDoct** [comment] 2018-08-07 15:08
A new issue. After setting a pin as output, it's not possible to set it as an input again... There's a command:error returned...

**Comment by andrethomas** [comment] 2018-08-07 15:41
I see... looking into it.

**Comment by andrethomas** [comment] 2018-08-07 15:48
Fixed by https://github.com/andrethomas/Sonoff-Tasmota/commit/6656043da36712bce309e46d1dc741525d6fa2a6

**Comment by andrethomas** [comment] 2018-08-07 15:50
@MadDoct Now you'll need to make a PR to merge changes in andrethomas:mcp230xx_output to your fork of mcp230xx_output :)

**Comment by MadDoct** [comment] 2018-08-07 15:52
Thanks again!

**Comment by jsponz** [comment] 2018-08-07 17:04
@MadDoct Excellent! Could you share your final configuration? 
Thanks in advance!

**Comment by andrethomas** [comment] 2018-08-07 17:07
@jsponz What do you mean by final configuration?

**Comment by MadDoct** [comment] 2018-08-07 17:54
I don't understant either...
You must compile @andrethomas' mcp230xx output branch.
It will include all the enhancements we talked about here...

**Comment by MadDoct** [comment] 2018-08-07 17:55
@andrethomas , could you create a wiki about the output features and usage?

**Comment by MadDoct** [comment] 2018-08-07 17:55
(i know them well, but would be good for others...)

**Comment by andrethomas** [comment] 2018-08-07 18:03
sensor29 commands are extended as follows:

`sensor29 pin,pinmode,pullup`

pin = pin number of MCP device
pinmode = 5 for output (1 through 4 already documented in Wiki link below)
pullup = 0 default to LOW on power-up/reset
pullup = 1 default to HIGH on power-up/reset
**If SAVE_STATE is enabled, then pull-up is ignored during reset/power-up**

Once pin is in pinmode 5 the followng commands turn pin on and off
`sensor29 pin,ON // Turn pin on`
`sensor29 pin,OFF // Turn pin off`
`sensor29 pin,T // Toggle current state of pin`

I'll add it to the Wiki if and when it gets merged with the development branch.

All the other functions described in the Wiki here https://github.com/arendst/Sonoff-Tasmota/wiki/MCP23008-MCP23017 are the same

**Comment by andrethomas** [comment] 2018-08-07 18:33
I've added information to the current Wiki at the very bottom for experimental use on OUTPUT functionality.

**Comment by MadDoct** [comment] 2018-08-07 19:27
@andrethomas , is it possible to change telemetry information to show the output pins as such and their state?

**Comment by andrethomas** [comment] 2018-08-07 19:30
Could probably add {"D":pin,"M":pinmode,"S":currentstate} to telemetry data...

**Comment by andrethomas** [comment] 2018-08-07 19:31
Not sure how it would be useful though...

**Comment by andrethomas** [comment] 2018-08-07 20:49
Could do this
```
21:47:33 MQT: tele/sonoff/SENSOR = {"Time":"2018-08-07T21:47:33","MCP230XX":{"D0":0,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":0}}
21:47:39 MQT: tele/sonoff/SENSOR = {"MCP230_OUT": {"OUTD0":0,"OUTD4":0,"EO":0}}
```

**Comment by andrethomas** [comment] 2018-08-07 21:03
```
22:03:02 MQT: tele/sonoff/SENSOR = {"Time":"2018-08-07T22:03:02","MCP230XX":{"D0":0,"D1":0,"D2":0,"D3":0,"D4":0,"D5":0,"D6":0,"D7":0}}
22:03:02 MQT: tele/sonoff/SENSOR = {"Time":"2018-08-07T22:03:02","MCP230_OUT": {"OUTD0":0,"OUTD4":0,"END":1}}
```

Better :)

**Comment by andrethomas** [comment] 2018-08-07 21:29
Perhaps when merged with development it can be combined. I do not want to remove data from the original telemetry data at this point.

**Comment by MadDoct** [comment] 2018-08-08 10:03
I forked from stefanbode to have shutters support, but replaced the mcp230xx with yours to have the best of both worlds and made a pull request to include your work in his fork... (with due credits!)
By the way, wouldn't it be possible for you to do to the mcp the se that he did to the pcf8574a, integrating it to the point of using it to drive relays, as if they were "stock"?

**Comment by andrethomas** [comment] 2018-09-11 05:40
@petez69 You will have bouncing unless you either enable the internal pull-up resistor, or externally bias it with a resistor to pull down or up.

As per the wiki
`sensor29 pin,pinmode,pullup,intmode`
pullup needs to be 1 for using the internal pullup resistor

**Comment by petez69** [comment] 2018-09-11 06:07
Understand the pullup component.  Read the wiki again and it says the max poll rate is 50ms anyway, this should be enough to stop debounce....I have some units coming and experiment...

Thankyou

**Comment by andrethomas** [comment] 2018-09-11 06:15
👍 I use intpri,4 which = ~200ms on a push-button panel
