### ISSUE TITLE
Sonoff T4EU1C, Flashed ok but unable to get AP mode

### ISSUE THREAD

**Issue by c3reeman** [arendst/Sonoff-Tasmota#6459] opened 2019-09-19 12:11 UTC
Has anyone successfully flashed and connected the new sonoff T4EU1C switch’s.

I’ve managed a successful flash after grounding GPIO0 directly off the esp8266 chip leg, but after a restart it doesn’t appear to start an access point to get WiFi connected, I connected using termite and I can see tasmota is running and I’m able to enter WiFi user and password using termite but unfortunately the log from termite and tasmota still reports unable to connect.

**Comment by effelle** [comment] 2019-09-19 12:54
Possible duplicate of #6248.
Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for **Tasmota software feature requests and bug reporting**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Closed** 2019-09-20 21:52 UTC
